// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hackathon/messages/page_svc/create_request.proto

package page_svc

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HackathonId   string                 `protobuf:"bytes,1,opt,name=hackathon_id,json=hackathonId,proto3" json:"hackathon_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Visible       bool                   `protobuf:"varint,4,opt,name=visible,proto3" json:"visible,omitempty"` // order is automatically assigned by backend (max(order) + 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_hackathon_messages_page_svc_create_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hackathon_messages_page_svc_create_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_hackathon_messages_page_svc_create_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetHackathonId() string {
	if x != nil {
		return x.HackathonId
	}
	return ""
}

func (x *CreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

var File_hackathon_messages_page_svc_create_request_proto protoreflect.FileDescriptor

const file_hackathon_messages_page_svc_create_request_proto_rawDesc = "" +
	"\n" +
	"0hackathon/messages/page_svc/create_request.proto\x12\x1bhackathon.messages.page_svc\x1a\x1bbuf/validate/validate.proto\"\x9c\x01\n" +
	"\rCreateRequest\x12+\n" +
	"\fhackathon_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\vhackathonId\x12 \n" +
	"\x05title\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x03\x18\xff\x01R\x05title\x12\"\n" +
	"\acontent\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x90NR\acontent\x12\x18\n" +
	"\avisible\x18\x04 \x01(\bR\avisibleBjZhgithub.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/messages/page_svcb\x06proto3"

var (
	file_hackathon_messages_page_svc_create_request_proto_rawDescOnce sync.Once
	file_hackathon_messages_page_svc_create_request_proto_rawDescData []byte
)

func file_hackathon_messages_page_svc_create_request_proto_rawDescGZIP() []byte {
	file_hackathon_messages_page_svc_create_request_proto_rawDescOnce.Do(func() {
		file_hackathon_messages_page_svc_create_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hackathon_messages_page_svc_create_request_proto_rawDesc), len(file_hackathon_messages_page_svc_create_request_proto_rawDesc)))
	})
	return file_hackathon_messages_page_svc_create_request_proto_rawDescData
}

var file_hackathon_messages_page_svc_create_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hackathon_messages_page_svc_create_request_proto_goTypes = []any{
	(*CreateRequest)(nil), // 0: hackathon.messages.page_svc.CreateRequest
}
var file_hackathon_messages_page_svc_create_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hackathon_messages_page_svc_create_request_proto_init() }
func file_hackathon_messages_page_svc_create_request_proto_init() {
	if File_hackathon_messages_page_svc_create_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hackathon_messages_page_svc_create_request_proto_rawDesc), len(file_hackathon_messages_page_svc_create_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hackathon_messages_page_svc_create_request_proto_goTypes,
		DependencyIndexes: file_hackathon_messages_page_svc_create_request_proto_depIdxs,
		MessageInfos:      file_hackathon_messages_page_svc_create_request_proto_msgTypes,
	}.Build()
	File_hackathon_messages_page_svc_create_request_proto = out.File
	file_hackathon_messages_page_svc_create_request_proto_goTypes = nil
	file_hackathon_messages_page_svc_create_request_proto_depIdxs = nil
}
