// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: hackathon/page_service.proto

package hackathon

import (
	context "context"
	page_svc "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/messages/page_svc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PageService_List_FullMethodName     = "/hackathon.PageService/List"
	PageService_Get_FullMethodName      = "/hackathon.PageService/Get"
	PageService_Create_FullMethodName   = "/hackathon.PageService/Create"
	PageService_Edit_FullMethodName     = "/hackathon.PageService/Edit"
	PageService_Delete_FullMethodName   = "/hackathon.PageService/Delete"
	PageService_MoveUp_FullMethodName   = "/hackathon.PageService/MoveUp"
	PageService_MoveDown_FullMethodName = "/hackathon.PageService/MoveDown"
	PageService_SetOrder_FullMethodName = "/hackathon.PageService/SetOrder"
)

// PageServiceClient is the client API for PageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PageServiceClient interface {
	List(ctx context.Context, in *page_svc.ListRequest, opts ...grpc.CallOption) (*page_svc.ListResponse, error)
	Get(ctx context.Context, in *page_svc.GetRequest, opts ...grpc.CallOption) (*page_svc.GetResponse, error)
	Create(ctx context.Context, in *page_svc.CreateRequest, opts ...grpc.CallOption) (*page_svc.CreateResponse, error)
	Edit(ctx context.Context, in *page_svc.EditRequest, opts ...grpc.CallOption) (*page_svc.EditResponse, error)
	Delete(ctx context.Context, in *page_svc.DeleteRequest, opts ...grpc.CallOption) (*page_svc.DeleteResponse, error)
	// Reordering methods - backend manages order uniqueness
	MoveUp(ctx context.Context, in *page_svc.MoveUpRequest, opts ...grpc.CallOption) (*page_svc.MoveUpResponse, error)
	MoveDown(ctx context.Context, in *page_svc.MoveDownRequest, opts ...grpc.CallOption) (*page_svc.MoveDownResponse, error)
	SetOrder(ctx context.Context, in *page_svc.SetOrderRequest, opts ...grpc.CallOption) (*page_svc.SetOrderResponse, error)
}

type pageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPageServiceClient(cc grpc.ClientConnInterface) PageServiceClient {
	return &pageServiceClient{cc}
}

func (c *pageServiceClient) List(ctx context.Context, in *page_svc.ListRequest, opts ...grpc.CallOption) (*page_svc.ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(page_svc.ListResponse)
	err := c.cc.Invoke(ctx, PageService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Get(ctx context.Context, in *page_svc.GetRequest, opts ...grpc.CallOption) (*page_svc.GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(page_svc.GetResponse)
	err := c.cc.Invoke(ctx, PageService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Create(ctx context.Context, in *page_svc.CreateRequest, opts ...grpc.CallOption) (*page_svc.CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(page_svc.CreateResponse)
	err := c.cc.Invoke(ctx, PageService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Edit(ctx context.Context, in *page_svc.EditRequest, opts ...grpc.CallOption) (*page_svc.EditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(page_svc.EditResponse)
	err := c.cc.Invoke(ctx, PageService_Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Delete(ctx context.Context, in *page_svc.DeleteRequest, opts ...grpc.CallOption) (*page_svc.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(page_svc.DeleteResponse)
	err := c.cc.Invoke(ctx, PageService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) MoveUp(ctx context.Context, in *page_svc.MoveUpRequest, opts ...grpc.CallOption) (*page_svc.MoveUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(page_svc.MoveUpResponse)
	err := c.cc.Invoke(ctx, PageService_MoveUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) MoveDown(ctx context.Context, in *page_svc.MoveDownRequest, opts ...grpc.CallOption) (*page_svc.MoveDownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(page_svc.MoveDownResponse)
	err := c.cc.Invoke(ctx, PageService_MoveDown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) SetOrder(ctx context.Context, in *page_svc.SetOrderRequest, opts ...grpc.CallOption) (*page_svc.SetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(page_svc.SetOrderResponse)
	err := c.cc.Invoke(ctx, PageService_SetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageServiceServer is the server API for PageService service.
// All implementations must embed UnimplementedPageServiceServer
// for forward compatibility.
type PageServiceServer interface {
	List(context.Context, *page_svc.ListRequest) (*page_svc.ListResponse, error)
	Get(context.Context, *page_svc.GetRequest) (*page_svc.GetResponse, error)
	Create(context.Context, *page_svc.CreateRequest) (*page_svc.CreateResponse, error)
	Edit(context.Context, *page_svc.EditRequest) (*page_svc.EditResponse, error)
	Delete(context.Context, *page_svc.DeleteRequest) (*page_svc.DeleteResponse, error)
	// Reordering methods - backend manages order uniqueness
	MoveUp(context.Context, *page_svc.MoveUpRequest) (*page_svc.MoveUpResponse, error)
	MoveDown(context.Context, *page_svc.MoveDownRequest) (*page_svc.MoveDownResponse, error)
	SetOrder(context.Context, *page_svc.SetOrderRequest) (*page_svc.SetOrderResponse, error)
	mustEmbedUnimplementedPageServiceServer()
}

// UnimplementedPageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPageServiceServer struct{}

func (UnimplementedPageServiceServer) List(context.Context, *page_svc.ListRequest) (*page_svc.ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPageServiceServer) Get(context.Context, *page_svc.GetRequest) (*page_svc.GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPageServiceServer) Create(context.Context, *page_svc.CreateRequest) (*page_svc.CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPageServiceServer) Edit(context.Context, *page_svc.EditRequest) (*page_svc.EditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedPageServiceServer) Delete(context.Context, *page_svc.DeleteRequest) (*page_svc.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPageServiceServer) MoveUp(context.Context, *page_svc.MoveUpRequest) (*page_svc.MoveUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveUp not implemented")
}
func (UnimplementedPageServiceServer) MoveDown(context.Context, *page_svc.MoveDownRequest) (*page_svc.MoveDownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveDown not implemented")
}
func (UnimplementedPageServiceServer) SetOrder(context.Context, *page_svc.SetOrderRequest) (*page_svc.SetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOrder not implemented")
}
func (UnimplementedPageServiceServer) mustEmbedUnimplementedPageServiceServer() {}
func (UnimplementedPageServiceServer) testEmbeddedByValue()                     {}

// UnsafePageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PageServiceServer will
// result in compilation errors.
type UnsafePageServiceServer interface {
	mustEmbedUnimplementedPageServiceServer()
}

func RegisterPageServiceServer(s grpc.ServiceRegistrar, srv PageServiceServer) {
	// If the following call panics, it indicates UnimplementedPageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PageService_ServiceDesc, srv)
}

func _PageService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(page_svc.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).List(ctx, req.(*page_svc.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(page_svc.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).Get(ctx, req.(*page_svc.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(page_svc.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).Create(ctx, req.(*page_svc.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(page_svc.EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).Edit(ctx, req.(*page_svc.EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(page_svc.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).Delete(ctx, req.(*page_svc.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_MoveUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(page_svc.MoveUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).MoveUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_MoveUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).MoveUp(ctx, req.(*page_svc.MoveUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_MoveDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(page_svc.MoveDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).MoveDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_MoveDown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).MoveDown(ctx, req.(*page_svc.MoveDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_SetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(page_svc.SetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).SetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageService_SetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).SetOrder(ctx, req.(*page_svc.SetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PageService_ServiceDesc is the grpc.ServiceDesc for PageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hackathon.PageService",
	HandlerType: (*PageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PageService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PageService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PageService_Create_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _PageService_Edit_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PageService_Delete_Handler,
		},
		{
			MethodName: "MoveUp",
			Handler:    _PageService_MoveUp_Handler,
		},
		{
			MethodName: "MoveDown",
			Handler:    _PageService_MoveDown_Handler,
		},
		{
			MethodName: "SetOrder",
			Handler:    _PageService_SetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hackathon/page_service.proto",
}
