// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: hackathon/phase_service.proto

package hackathon

import (
	context "context"
	phase_svc "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/messages/phase_svc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PhaseService_List_FullMethodName   = "/hackathon.PhaseService/List"
	PhaseService_Get_FullMethodName    = "/hackathon.PhaseService/Get"
	PhaseService_Create_FullMethodName = "/hackathon.PhaseService/Create"
	PhaseService_Edit_FullMethodName   = "/hackathon.PhaseService/Edit"
	PhaseService_Delete_FullMethodName = "/hackathon.PhaseService/Delete"
)

// PhaseServiceClient is the client API for PhaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhaseServiceClient interface {
	List(ctx context.Context, in *phase_svc.ListRequest, opts ...grpc.CallOption) (*phase_svc.ListResponse, error)
	Get(ctx context.Context, in *phase_svc.GetRequest, opts ...grpc.CallOption) (*phase_svc.GetResponse, error)
	Create(ctx context.Context, in *phase_svc.CreateRequest, opts ...grpc.CallOption) (*phase_svc.CreateResponse, error)
	Edit(ctx context.Context, in *phase_svc.EditRequest, opts ...grpc.CallOption) (*phase_svc.EditResponse, error)
	Delete(ctx context.Context, in *phase_svc.DeleteRequest, opts ...grpc.CallOption) (*phase_svc.DeleteResponse, error)
}

type phaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhaseServiceClient(cc grpc.ClientConnInterface) PhaseServiceClient {
	return &phaseServiceClient{cc}
}

func (c *phaseServiceClient) List(ctx context.Context, in *phase_svc.ListRequest, opts ...grpc.CallOption) (*phase_svc.ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(phase_svc.ListResponse)
	err := c.cc.Invoke(ctx, PhaseService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phaseServiceClient) Get(ctx context.Context, in *phase_svc.GetRequest, opts ...grpc.CallOption) (*phase_svc.GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(phase_svc.GetResponse)
	err := c.cc.Invoke(ctx, PhaseService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phaseServiceClient) Create(ctx context.Context, in *phase_svc.CreateRequest, opts ...grpc.CallOption) (*phase_svc.CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(phase_svc.CreateResponse)
	err := c.cc.Invoke(ctx, PhaseService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phaseServiceClient) Edit(ctx context.Context, in *phase_svc.EditRequest, opts ...grpc.CallOption) (*phase_svc.EditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(phase_svc.EditResponse)
	err := c.cc.Invoke(ctx, PhaseService_Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phaseServiceClient) Delete(ctx context.Context, in *phase_svc.DeleteRequest, opts ...grpc.CallOption) (*phase_svc.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(phase_svc.DeleteResponse)
	err := c.cc.Invoke(ctx, PhaseService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhaseServiceServer is the server API for PhaseService service.
// All implementations must embed UnimplementedPhaseServiceServer
// for forward compatibility.
type PhaseServiceServer interface {
	List(context.Context, *phase_svc.ListRequest) (*phase_svc.ListResponse, error)
	Get(context.Context, *phase_svc.GetRequest) (*phase_svc.GetResponse, error)
	Create(context.Context, *phase_svc.CreateRequest) (*phase_svc.CreateResponse, error)
	Edit(context.Context, *phase_svc.EditRequest) (*phase_svc.EditResponse, error)
	Delete(context.Context, *phase_svc.DeleteRequest) (*phase_svc.DeleteResponse, error)
	mustEmbedUnimplementedPhaseServiceServer()
}

// UnimplementedPhaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPhaseServiceServer struct{}

func (UnimplementedPhaseServiceServer) List(context.Context, *phase_svc.ListRequest) (*phase_svc.ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPhaseServiceServer) Get(context.Context, *phase_svc.GetRequest) (*phase_svc.GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPhaseServiceServer) Create(context.Context, *phase_svc.CreateRequest) (*phase_svc.CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPhaseServiceServer) Edit(context.Context, *phase_svc.EditRequest) (*phase_svc.EditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedPhaseServiceServer) Delete(context.Context, *phase_svc.DeleteRequest) (*phase_svc.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPhaseServiceServer) mustEmbedUnimplementedPhaseServiceServer() {}
func (UnimplementedPhaseServiceServer) testEmbeddedByValue()                      {}

// UnsafePhaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhaseServiceServer will
// result in compilation errors.
type UnsafePhaseServiceServer interface {
	mustEmbedUnimplementedPhaseServiceServer()
}

func RegisterPhaseServiceServer(s grpc.ServiceRegistrar, srv PhaseServiceServer) {
	// If the following call panics, it indicates UnimplementedPhaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PhaseService_ServiceDesc, srv)
}

func _PhaseService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(phase_svc.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseServiceServer).List(ctx, req.(*phase_svc.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhaseService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(phase_svc.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseServiceServer).Get(ctx, req.(*phase_svc.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhaseService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(phase_svc.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseServiceServer).Create(ctx, req.(*phase_svc.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhaseService_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(phase_svc.EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseServiceServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseService_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseServiceServer).Edit(ctx, req.(*phase_svc.EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhaseService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(phase_svc.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseServiceServer).Delete(ctx, req.(*phase_svc.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhaseService_ServiceDesc is the grpc.ServiceDesc for PhaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hackathon.PhaseService",
	HandlerType: (*PhaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PhaseService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PhaseService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PhaseService_Create_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _PhaseService_Edit_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PhaseService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hackathon/phase_service.proto",
}
