// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hackathon/phase_service.proto

package hackathon

import (
	phase_svc "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/messages/phase_svc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hackathon_phase_service_proto protoreflect.FileDescriptor

const file_hackathon_phase_service_proto_rawDesc = "" +
	"\n" +
	"\x1dhackathon/phase_service.proto\x12\thackathon\x1a1hackathon/messages/phase_svc/create_request.proto\x1a2hackathon/messages/phase_svc/create_response.proto\x1a1hackathon/messages/phase_svc/delete_request.proto\x1a2hackathon/messages/phase_svc/delete_response.proto\x1a/hackathon/messages/phase_svc/edit_request.proto\x1a0hackathon/messages/phase_svc/edit_response.proto\x1a.hackathon/messages/phase_svc/get_request.proto\x1a/hackathon/messages/phase_svc/get_response.proto\x1a/hackathon/messages/phase_svc/list_request.proto\x1a0hackathon/messages/phase_svc/list_response.proto2\xf2\x03\n" +
	"\fPhaseService\x12]\n" +
	"\x04List\x12).hackathon.messages.phase_svc.ListRequest\x1a*.hackathon.messages.phase_svc.ListResponse\x12Z\n" +
	"\x03Get\x12(.hackathon.messages.phase_svc.GetRequest\x1a).hackathon.messages.phase_svc.GetResponse\x12c\n" +
	"\x06Create\x12+.hackathon.messages.phase_svc.CreateRequest\x1a,.hackathon.messages.phase_svc.CreateResponse\x12]\n" +
	"\x04Edit\x12).hackathon.messages.phase_svc.EditRequest\x1a*.hackathon.messages.phase_svc.EditResponse\x12c\n" +
	"\x06Delete\x12+.hackathon.messages.phase_svc.DeleteRequest\x1a,.hackathon.messages.phase_svc.DeleteResponseBXZVgithub.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathonb\x06proto3"

var file_hackathon_phase_service_proto_goTypes = []any{
	(*phase_svc.ListRequest)(nil),    // 0: hackathon.messages.phase_svc.ListRequest
	(*phase_svc.GetRequest)(nil),     // 1: hackathon.messages.phase_svc.GetRequest
	(*phase_svc.CreateRequest)(nil),  // 2: hackathon.messages.phase_svc.CreateRequest
	(*phase_svc.EditRequest)(nil),    // 3: hackathon.messages.phase_svc.EditRequest
	(*phase_svc.DeleteRequest)(nil),  // 4: hackathon.messages.phase_svc.DeleteRequest
	(*phase_svc.ListResponse)(nil),   // 5: hackathon.messages.phase_svc.ListResponse
	(*phase_svc.GetResponse)(nil),    // 6: hackathon.messages.phase_svc.GetResponse
	(*phase_svc.CreateResponse)(nil), // 7: hackathon.messages.phase_svc.CreateResponse
	(*phase_svc.EditResponse)(nil),   // 8: hackathon.messages.phase_svc.EditResponse
	(*phase_svc.DeleteResponse)(nil), // 9: hackathon.messages.phase_svc.DeleteResponse
}
var file_hackathon_phase_service_proto_depIdxs = []int32{
	0, // 0: hackathon.PhaseService.List:input_type -> hackathon.messages.phase_svc.ListRequest
	1, // 1: hackathon.PhaseService.Get:input_type -> hackathon.messages.phase_svc.GetRequest
	2, // 2: hackathon.PhaseService.Create:input_type -> hackathon.messages.phase_svc.CreateRequest
	3, // 3: hackathon.PhaseService.Edit:input_type -> hackathon.messages.phase_svc.EditRequest
	4, // 4: hackathon.PhaseService.Delete:input_type -> hackathon.messages.phase_svc.DeleteRequest
	5, // 5: hackathon.PhaseService.List:output_type -> hackathon.messages.phase_svc.ListResponse
	6, // 6: hackathon.PhaseService.Get:output_type -> hackathon.messages.phase_svc.GetResponse
	7, // 7: hackathon.PhaseService.Create:output_type -> hackathon.messages.phase_svc.CreateResponse
	8, // 8: hackathon.PhaseService.Edit:output_type -> hackathon.messages.phase_svc.EditResponse
	9, // 9: hackathon.PhaseService.Delete:output_type -> hackathon.messages.phase_svc.DeleteResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hackathon_phase_service_proto_init() }
func file_hackathon_phase_service_proto_init() {
	if File_hackathon_phase_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hackathon_phase_service_proto_rawDesc), len(file_hackathon_phase_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hackathon_phase_service_proto_goTypes,
		DependencyIndexes: file_hackathon_phase_service_proto_depIdxs,
	}.Build()
	File_hackathon_phase_service_proto = out.File
	file_hackathon_phase_service_proto_goTypes = nil
	file_hackathon_phase_service_proto_depIdxs = nil
}
