// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: hackathon/public_service.proto

package hackathon

import (
	context "context"
	public_svc "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/messages/public_svc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicService_ListHackathons_FullMethodName = "/hackathon.PublicService/ListHackathons"
	PublicService_GetHackathon_FullMethodName   = "/hackathon.PublicService/GetHackathon"
)

// PublicServiceClient is the client API for PublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Everything an anonymous visitor may read, and the only service that serves
// them. Every method here is readable without a token and returns data for public
// hackathons only. A private hackathon is answered as NotFound rather than
// PermissionDenied: its existence is not a visitor's business either.
type PublicServiceClient interface {
	// The public hackathon directory.
	ListHackathons(ctx context.Context, in *public_svc.ListHackathonsRequest, opts ...grpc.CallOption) (*public_svc.ListHackathonsResponse, error)
	// One public hackathon and everything published about it, in a single call.
	GetHackathon(ctx context.Context, in *public_svc.GetHackathonRequest, opts ...grpc.CallOption) (*public_svc.GetHackathonResponse, error)
}

type publicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicServiceClient(cc grpc.ClientConnInterface) PublicServiceClient {
	return &publicServiceClient{cc}
}

func (c *publicServiceClient) ListHackathons(ctx context.Context, in *public_svc.ListHackathonsRequest, opts ...grpc.CallOption) (*public_svc.ListHackathonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(public_svc.ListHackathonsResponse)
	err := c.cc.Invoke(ctx, PublicService_ListHackathons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicServiceClient) GetHackathon(ctx context.Context, in *public_svc.GetHackathonRequest, opts ...grpc.CallOption) (*public_svc.GetHackathonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(public_svc.GetHackathonResponse)
	err := c.cc.Invoke(ctx, PublicService_GetHackathon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicServiceServer is the server API for PublicService service.
// All implementations must embed UnimplementedPublicServiceServer
// for forward compatibility.
//
// Everything an anonymous visitor may read, and the only service that serves
// them. Every method here is readable without a token and returns data for public
// hackathons only. A private hackathon is answered as NotFound rather than
// PermissionDenied: its existence is not a visitor's business either.
type PublicServiceServer interface {
	// The public hackathon directory.
	ListHackathons(context.Context, *public_svc.ListHackathonsRequest) (*public_svc.ListHackathonsResponse, error)
	// One public hackathon and everything published about it, in a single call.
	GetHackathon(context.Context, *public_svc.GetHackathonRequest) (*public_svc.GetHackathonResponse, error)
	mustEmbedUnimplementedPublicServiceServer()
}

// UnimplementedPublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicServiceServer struct{}

func (UnimplementedPublicServiceServer) ListHackathons(context.Context, *public_svc.ListHackathonsRequest) (*public_svc.ListHackathonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHackathons not implemented")
}
func (UnimplementedPublicServiceServer) GetHackathon(context.Context, *public_svc.GetHackathonRequest) (*public_svc.GetHackathonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHackathon not implemented")
}
func (UnimplementedPublicServiceServer) mustEmbedUnimplementedPublicServiceServer() {}
func (UnimplementedPublicServiceServer) testEmbeddedByValue()                       {}

// UnsafePublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicServiceServer will
// result in compilation errors.
type UnsafePublicServiceServer interface {
	mustEmbedUnimplementedPublicServiceServer()
}

func RegisterPublicServiceServer(s grpc.ServiceRegistrar, srv PublicServiceServer) {
	// If the following call panics, it indicates UnimplementedPublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicService_ServiceDesc, srv)
}

func _PublicService_ListHackathons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(public_svc.ListHackathonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).ListHackathons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_ListHackathons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).ListHackathons(ctx, req.(*public_svc.ListHackathonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicService_GetHackathon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(public_svc.GetHackathonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicServiceServer).GetHackathon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicService_GetHackathon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicServiceServer).GetHackathon(ctx, req.(*public_svc.GetHackathonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicService_ServiceDesc is the grpc.ServiceDesc for PublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hackathon.PublicService",
	HandlerType: (*PublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHackathons",
			Handler:    _PublicService_ListHackathons_Handler,
		},
		{
			MethodName: "GetHackathon",
			Handler:    _PublicService_GetHackathon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hackathon/public_service.proto",
}
