// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: hackathon/track_service.proto

package hackathon

import (
	context "context"
	track_svc "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/messages/track_svc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrackService_List_FullMethodName   = "/hackathon.TrackService/List"
	TrackService_Get_FullMethodName    = "/hackathon.TrackService/Get"
	TrackService_Create_FullMethodName = "/hackathon.TrackService/Create"
	TrackService_Edit_FullMethodName   = "/hackathon.TrackService/Edit"
	TrackService_Delete_FullMethodName = "/hackathon.TrackService/Delete"
)

// TrackServiceClient is the client API for TrackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrackServiceClient interface {
	List(ctx context.Context, in *track_svc.ListRequest, opts ...grpc.CallOption) (*track_svc.ListResponse, error)
	Get(ctx context.Context, in *track_svc.GetRequest, opts ...grpc.CallOption) (*track_svc.GetResponse, error)
	Create(ctx context.Context, in *track_svc.CreateRequest, opts ...grpc.CallOption) (*track_svc.CreateResponse, error)
	Edit(ctx context.Context, in *track_svc.EditRequest, opts ...grpc.CallOption) (*track_svc.EditResponse, error)
	Delete(ctx context.Context, in *track_svc.DeleteRequest, opts ...grpc.CallOption) (*track_svc.DeleteResponse, error)
}

type trackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackServiceClient(cc grpc.ClientConnInterface) TrackServiceClient {
	return &trackServiceClient{cc}
}

func (c *trackServiceClient) List(ctx context.Context, in *track_svc.ListRequest, opts ...grpc.CallOption) (*track_svc.ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(track_svc.ListResponse)
	err := c.cc.Invoke(ctx, TrackService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) Get(ctx context.Context, in *track_svc.GetRequest, opts ...grpc.CallOption) (*track_svc.GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(track_svc.GetResponse)
	err := c.cc.Invoke(ctx, TrackService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) Create(ctx context.Context, in *track_svc.CreateRequest, opts ...grpc.CallOption) (*track_svc.CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(track_svc.CreateResponse)
	err := c.cc.Invoke(ctx, TrackService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) Edit(ctx context.Context, in *track_svc.EditRequest, opts ...grpc.CallOption) (*track_svc.EditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(track_svc.EditResponse)
	err := c.cc.Invoke(ctx, TrackService_Edit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackServiceClient) Delete(ctx context.Context, in *track_svc.DeleteRequest, opts ...grpc.CallOption) (*track_svc.DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(track_svc.DeleteResponse)
	err := c.cc.Invoke(ctx, TrackService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackServiceServer is the server API for TrackService service.
// All implementations must embed UnimplementedTrackServiceServer
// for forward compatibility.
type TrackServiceServer interface {
	List(context.Context, *track_svc.ListRequest) (*track_svc.ListResponse, error)
	Get(context.Context, *track_svc.GetRequest) (*track_svc.GetResponse, error)
	Create(context.Context, *track_svc.CreateRequest) (*track_svc.CreateResponse, error)
	Edit(context.Context, *track_svc.EditRequest) (*track_svc.EditResponse, error)
	Delete(context.Context, *track_svc.DeleteRequest) (*track_svc.DeleteResponse, error)
	mustEmbedUnimplementedTrackServiceServer()
}

// UnimplementedTrackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackServiceServer struct{}

func (UnimplementedTrackServiceServer) List(context.Context, *track_svc.ListRequest) (*track_svc.ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTrackServiceServer) Get(context.Context, *track_svc.GetRequest) (*track_svc.GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTrackServiceServer) Create(context.Context, *track_svc.CreateRequest) (*track_svc.CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTrackServiceServer) Edit(context.Context, *track_svc.EditRequest) (*track_svc.EditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedTrackServiceServer) Delete(context.Context, *track_svc.DeleteRequest) (*track_svc.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTrackServiceServer) mustEmbedUnimplementedTrackServiceServer() {}
func (UnimplementedTrackServiceServer) testEmbeddedByValue()                      {}

// UnsafeTrackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackServiceServer will
// result in compilation errors.
type UnsafeTrackServiceServer interface {
	mustEmbedUnimplementedTrackServiceServer()
}

func RegisterTrackServiceServer(s grpc.ServiceRegistrar, srv TrackServiceServer) {
	// If the following call panics, it indicates UnimplementedTrackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrackService_ServiceDesc, srv)
}

func _TrackService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(track_svc.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).List(ctx, req.(*track_svc.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(track_svc.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).Get(ctx, req.(*track_svc.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(track_svc.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).Create(ctx, req.(*track_svc.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(track_svc.EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_Edit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).Edit(ctx, req.(*track_svc.EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(track_svc.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrackService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackServiceServer).Delete(ctx, req.(*track_svc.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrackService_ServiceDesc is the grpc.ServiceDesc for TrackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hackathon.TrackService",
	HandlerType: (*TrackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _TrackService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TrackService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TrackService_Create_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _TrackService_Edit_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TrackService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hackathon/track_service.proto",
}
