// Code generated by ent, DO NOT EDIT.

package hackathoninvite

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the hackathoninvite type in the database.
	Label = "hackathon_invite"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeHackathon holds the string denoting the hackathon edge name in mutations.
	EdgeHackathon = "hackathon"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// Table holds the table name of the hackathoninvite in the database.
	Table = "hackathon_invites"
	// HackathonTable is the table that holds the hackathon relation/edge.
	HackathonTable = "hackathon_invites"
	// HackathonInverseTable is the table name for the Hackathon entity.
	// It exists in this package in order to avoid circular dependency with the "hackathon" package.
	HackathonInverseTable = "hackathons"
	// HackathonColumn is the table column denoting the hackathon relation/edge.
	HackathonColumn = "hackathon_invite_hackathon"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "hackathon_invites"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "user_created_hackathon_invites"
)

// Columns holds all SQL columns for hackathoninvite fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldRevokedAt,
	FieldToken,
	FieldNote,
	FieldExpiresAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "hackathon_invites"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"hackathon_invite_hackathon",
	"user_created_hackathon_invites",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultToken holds the default value on creation for the "token" field.
	DefaultToken func() uuid.UUID
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the HackathonInvite queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByHackathonField orders the results by hackathon field.
func ByHackathonField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHackathonStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}
func newHackathonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HackathonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, HackathonTable, HackathonColumn),
	)
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
