name: global
version: 0.1.0
language: none

targets:
  lint:
    steps:
      - runner: general
      - runner: symlink
    inputs: ["self"]

  lint-security:
    tags:
      - allow-failure
    steps:
      - runner: trivy
    inputs: ["self"]
