// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hackathon/messages/project_svc/set_preference_request.proto

package project_svc

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPreferenceRequest) Reset() {
	*x = SetPreferenceRequest{}
	mi := &file_hackathon_messages_project_svc_set_preference_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPreferenceRequest) ProtoMessage() {}

func (x *SetPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hackathon_messages_project_svc_set_preference_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPreferenceRequest.ProtoReflect.Descriptor instead.
func (*SetPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_hackathon_messages_project_svc_set_preference_request_proto_rawDescGZIP(), []int{0}
}

func (x *SetPreferenceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

var File_hackathon_messages_project_svc_set_preference_request_proto protoreflect.FileDescriptor

const file_hackathon_messages_project_svc_set_preference_request_proto_rawDesc = "" +
	"\n" +
	";hackathon/messages/project_svc/set_preference_request.proto\x12\x1ehackathon.messages.project_svc\x1a\x1bbuf/validate/validate.proto\"?\n" +
	"\x14SetPreferenceRequest\x12'\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tprojectIdBmZkgithub.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/messages/project_svcb\x06proto3"

var (
	file_hackathon_messages_project_svc_set_preference_request_proto_rawDescOnce sync.Once
	file_hackathon_messages_project_svc_set_preference_request_proto_rawDescData []byte
)

func file_hackathon_messages_project_svc_set_preference_request_proto_rawDescGZIP() []byte {
	file_hackathon_messages_project_svc_set_preference_request_proto_rawDescOnce.Do(func() {
		file_hackathon_messages_project_svc_set_preference_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hackathon_messages_project_svc_set_preference_request_proto_rawDesc), len(file_hackathon_messages_project_svc_set_preference_request_proto_rawDesc)))
	})
	return file_hackathon_messages_project_svc_set_preference_request_proto_rawDescData
}

var file_hackathon_messages_project_svc_set_preference_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hackathon_messages_project_svc_set_preference_request_proto_goTypes = []any{
	(*SetPreferenceRequest)(nil), // 0: hackathon.messages.project_svc.SetPreferenceRequest
}
var file_hackathon_messages_project_svc_set_preference_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hackathon_messages_project_svc_set_preference_request_proto_init() }
func file_hackathon_messages_project_svc_set_preference_request_proto_init() {
	if File_hackathon_messages_project_svc_set_preference_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hackathon_messages_project_svc_set_preference_request_proto_rawDesc), len(file_hackathon_messages_project_svc_set_preference_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hackathon_messages_project_svc_set_preference_request_proto_goTypes,
		DependencyIndexes: file_hackathon_messages_project_svc_set_preference_request_proto_depIdxs,
		MessageInfos:      file_hackathon_messages_project_svc_set_preference_request_proto_msgTypes,
	}.Build()
	File_hackathon_messages_project_svc_set_preference_request_proto = out.File
	file_hackathon_messages_project_svc_set_preference_request_proto_goTypes = nil
	file_hackathon_messages_project_svc_set_preference_request_proto_depIdxs = nil
}
