// Code generated by ent, DO NOT EDIT.

package voteresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the voteresult type in the database.
	Label = "vote_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldModifiedAt holds the string denoting the modified_at field in the database.
	FieldModifiedAt = "modified_at"
	// EdgeVoteCategory holds the string denoting the vote_category edge name in mutations.
	EdgeVoteCategory = "vote_category"
	// EdgeSubmission holds the string denoting the submission edge name in mutations.
	EdgeSubmission = "submission"
	// Table holds the table name of the voteresult in the database.
	Table = "vote_results"
	// VoteCategoryTable is the table that holds the vote_category relation/edge.
	VoteCategoryTable = "vote_results"
	// VoteCategoryInverseTable is the table name for the VoteCategory entity.
	// It exists in this package in order to avoid circular dependency with the "votecategory" package.
	VoteCategoryInverseTable = "vote_categories"
	// VoteCategoryColumn is the table column denoting the vote_category relation/edge.
	VoteCategoryColumn = "vote_category_results"
	// SubmissionTable is the table that holds the submission relation/edge.
	SubmissionTable = "vote_results"
	// SubmissionInverseTable is the table name for the Submission entity.
	// It exists in this package in order to avoid circular dependency with the "submission" package.
	SubmissionInverseTable = "submissions"
	// SubmissionColumn is the table column denoting the submission relation/edge.
	SubmissionColumn = "submission_vote_results"
)

// Columns holds all SQL columns for voteresult fields.
var Columns = []string{
	FieldID,
	FieldPosition,
	FieldTitle,
	FieldCreatedAt,
	FieldModifiedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "vote_results"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"submission_vote_results",
	"vote_category_results",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultModifiedAt holds the default value on creation for the "modified_at" field.
	DefaultModifiedAt func() time.Time
	// UpdateDefaultModifiedAt holds the default value on update for the "modified_at" field.
	UpdateDefaultModifiedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the VoteResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByModifiedAt orders the results by the modified_at field.
func ByModifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModifiedAt, opts...).ToFunc()
}

// ByVoteCategoryField orders the results by vote_category field.
func ByVoteCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVoteCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// BySubmissionField orders the results by submission field.
func BySubmissionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmissionStep(), sql.OrderByField(field, opts...))
	}
}
func newVoteCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VoteCategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VoteCategoryTable, VoteCategoryColumn),
	)
}
func newSubmissionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmissionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubmissionTable, SubmissionColumn),
	)
}
