// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Answer is the predicate function for answer builders.
type Answer func(*sql.Selector)

// Hackathon is the predicate function for hackathon builders.
type Hackathon func(*sql.Selector)

// HackathonInvite is the predicate function for hackathoninvite builders.
type HackathonInvite func(*sql.Selector)

// HackathonState is the predicate function for hackathonstate builders.
type HackathonState func(*sql.Selector)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// Participant is the predicate function for participant builders.
type Participant func(*sql.Selector)

// Phase is the predicate function for phase builders.
type Phase func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// Submission is the predicate function for submission builders.
type Submission func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// TeamParticipant is the predicate function for teamparticipant builders.
type TeamParticipant func(*sql.Selector)

// Track is the predicate function for track builders.
type Track func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vote is the predicate function for vote builders.
type Vote func(*sql.Selector)

// VoteCategory is the predicate function for votecategory builders.
type VoteCategory func(*sql.Selector)

// VoteResult is the predicate function for voteresult builders.
type VoteResult func(*sql.Selector)
