syntax = "proto3";

package hackathon;

import "hackathon/messages/hackathon_svc/add_owner_request.proto";
import "hackathon/messages/hackathon_svc/add_owner_response.proto";
import "hackathon/messages/hackathon_svc/create_request.proto";
import "hackathon/messages/hackathon_svc/create_response.proto";
import "hackathon/messages/hackathon_svc/get_request.proto";
import "hackathon/messages/hackathon_svc/get_response.proto";
import "hackathon/messages/hackathon_svc/join_request.proto";
import "hackathon/messages/hackathon_svc/join_response.proto";
import "hackathon/messages/hackathon_svc/list_request.proto";
import "hackathon/messages/hackathon_svc/list_response.proto";
import "hackathon/messages/hackathon_svc/remove_owner_request.proto";
import "hackathon/messages/hackathon_svc/remove_owner_response.proto";
import "hackathon/messages/hackathon_svc/remove_participant_request.proto";
import "hackathon/messages/hackathon_svc/remove_participant_response.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon";

service HackathonService {
  rpc List(hackathon.messages.hackathon_svc.ListRequest) returns (hackathon.messages.hackathon_svc.ListResponse);
  rpc Get(hackathon.messages.hackathon_svc.GetRequest) returns (hackathon.messages.hackathon_svc.GetResponse);
  rpc Create(hackathon.messages.hackathon_svc.CreateRequest) returns (hackathon.messages.hackathon_svc.CreateResponse);
  rpc Join(hackathon.messages.hackathon_svc.JoinRequest) returns (hackathon.messages.hackathon_svc.JoinResponse);
  rpc RemoveParticipant(hackathon.messages.hackathon_svc.RemoveParticipantRequest) returns (hackathon.messages.hackathon_svc.RemoveParticipantResponse);
  rpc AddOwner(hackathon.messages.hackathon_svc.AddOwnerRequest) returns (hackathon.messages.hackathon_svc.AddOwnerResponse);
  rpc RemoveOwner(hackathon.messages.hackathon_svc.RemoveOwnerRequest) returns (hackathon.messages.hackathon_svc.RemoveOwnerResponse);
}
