
syntax = "proto3";

package hackathon;

import "hackathon/messages/add_page_request.proto";
import "hackathon/messages/add_page_response.proto";
import "hackathon/messages/edit_page_request.proto";
import "hackathon/messages/edit_page_response.proto";
import "hackathon/messages/delete_page_request.proto";
import "hackathon/messages/delete_page_response.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon";

service PageService {
  rpc Add(hackathon.messages.AddPageRequest) returns (hackathon.messages.AddPageResponse);
  rpc Edit(hackathon.messages.EditPageRequest) returns (hackathon.messages.EditPageResponse);
  rpc Delete(hackathon.messages.DeletePageRequest) returns (hackathon.messages.DeletePageResponse);
}

