syntax = "proto3";

package hackathon;

import "hackathon/messages/team_svc/assign_user_request.proto";
import "hackathon/messages/team_svc/assign_user_response.proto";
import "hackathon/messages/team_svc/create_request.proto";
import "hackathon/messages/team_svc/create_response.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon";

service TeamService {
  rpc Create(hackathon.messages.team_svc.CreateRequest) returns (hackathon.messages.team_svc.CreateResponse);
  rpc AssignUser(hackathon.messages.team_svc.AssignUserRequest) returns (hackathon.messages.team_svc.AssignUserResponse);
}
