# shellcheck shell=bash
# Shared helpers. Source after setting HERE.

SKILL_DIR="$(dirname "$HERE")"
VENDOR="$SKILL_DIR/vendor"
STATE="$SKILL_DIR/.state"
PROJECT="${OPENREPLAY_PROJECT:-openreplay}"
# Pin upstream. Override with OPENREPLAY_REF=v1.x.y for a release tag.
UPSTREAM_REPO="${OPENREPLAY_REPO:-https://github.com/openreplay/openreplay.git}"
UPSTREAM_REF="${OPENREPLAY_REF:-main}"

mkdir -p "$STATE"

# Admin credentials for the OpenReplay UI/API — generated by scripts/signup.sh
# on first run, gitignored (skill .gitignore; also .env-ignored repo-wide).
# Lives OUTSIDE .state so that nothing which resets state deletes it: the
# password must survive down.sh, and surviving --volumes is what lets the next
# up.sh re-create the same account after a wipe.
SECRETS_FILE="$SKILL_DIR/.secrets.env"

# Fill unset OPENREPLAY_* variables from the secrets file. Explicit environment
# wins — an exported OPENREPLAY_PASSWORD is someone overriding on purpose.
# Plain KEY=value lines, no quoting: the value is everything after the first
# '=', so spaces survive without shell-quoting rules getting involved.
load_secrets() {
  [ -f "$SECRETS_FILE" ] || return 0
  local line k
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in ''|\#*) continue ;; esac
    k="${line%%=*}"
    case "$k" in *[!A-Za-z0-9_]*|'') continue ;; esac
    [ -n "${!k:-}" ] || export "$k=${line#*=}"
  done < "$SECRETS_FILE"
}

# Paths handed to docker.exe. On Git Bash/MSYS, MSYS_NO_PATHCONV stops the
# automatic POSIX→Windows translation (needed so docker's own /container/paths
# survive), which means a `/c/Users/...` argument reaches docker.exe verbatim
# and it resolves `C:\c\Users\...`. Hand it a Windows-style path instead;
# MSYS leaves those alone. Same fix as devcontainer-up/scripts/lib.sh.
COMPOSE_VENDOR="$VENDOR/docker-compose.yaml"
COMPOSE_OVERLAY="$SKILL_DIR/compose.tunnel.yaml"
COMPOSE_DIR="$VENDOR"
case "$(uname -s)" in
  MINGW* | MSYS*)
    export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL="*"
    COMPOSE_VENDOR="$(cygpath -m "$COMPOSE_VENDOR")"
    COMPOSE_OVERLAY="$(cygpath -m "$COMPOSE_OVERLAY")"
    COMPOSE_DIR="$(cygpath -m "$COMPOSE_DIR")"
    ;;
esac

compose() {
  docker compose -p "$PROJECT" \
    -f "$COMPOSE_VENDOR" -f "$COMPOSE_OVERLAY" \
    --project-directory "$COMPOSE_DIR" "$@"
}

require_docker() {
  command -v docker >/dev/null 2>&1 || { echo "error: docker not found" >&2; exit 1; }
  docker info >/dev/null 2>&1 || { echo "error: docker daemon not reachable" >&2; exit 1; }
}

require_vendor() {
  [ -f "$VENDOR/docker-compose.yaml" ] || {
    echo "error: upstream not fetched — run scripts/fetch-upstream.sh" >&2; exit 1; }
}

# ── named vs quick tunnel ────────────────────────────────────────────────────
# Same two modes as the app's own tunnel (see .claude/skills/lib/cf-api.sh for
# why named exists). Named when Cloudflare credentials and OPENREPLAY_HOSTNAME
# are configured; otherwise the quick tunnel, unchanged.
#
# The gain is largest here. COMMON_DOMAIN_NAME is baked into ~25 containers at
# boot, so a new hostname means rewriting common.env and recreating the whole
# stack — and every browser still carrying the old ingest URL posts sessions
# into a host that no longer exists, which looks exactly like "nobody visited".
# A stable hostname means the app's `replay.ingestPoint` wiring stays true.
# shellcheck source=../../lib/cf-named-tunnel.sh
source "$SKILL_DIR/../lib/cf-named-tunnel.sh"
NAMED_TUNNEL="${OPENREPLAY_TUNNEL_NAME:-hackagon-openreplay}"

named_configured() {
  cf_configured && [ -n "${OPENREPLAY_HOSTNAME:-}" ]
}

# The URL this rig is reachable on, asked of whatever is RUNNING — a named
# tunnel's container label, or the quick tunnel's log, which is the only place
# cloudflared ever prints it. Never the state file: a restarted tunnel has a new
# URL and the same state file, and a stale URL fails silently.
tunnel_url() {
  cfn_url "$NAMED_TUNNEL" 2>/dev/null && return 0
  docker logs "$(compose ps -q tunnel 2>/dev/null)" 2>&1 |
    grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' | tail -1
}

# The docker network a service is on, read off the live container. Upstream
# defines `openreplay-net` explicitly and compose prefixes it with the project
# name, so guessing it wrong is easy — and it fails as a DNS lookup for `caddy`
# INSIDE cloudflared, which Cloudflare renders as a plain 502 while every
# container reports healthy. That cost an afternoon once already.
rig_network() { # <service>
  docker inspect "$(compose ps -q "$1")" \
    --format '{{range $k,$v := .NetworkSettings.Networks}}{{$k}} {{end}}' 2>/dev/null |
    awk '{print $1}'
}
