#!/usr/bin/env bash
# Create the OpenReplay admin account non-interactively, from stored secrets.
#
# The stack ships with NO seeded account: the first signup at <url>/signup
# becomes the admin. An account created by hand with an unrecorded password
# means an unreachable dashboard whose only fix is `down.sh --volumes` — that
# has happened once already. So `up.sh` runs this after starting the stack:
#
#   /api/signup → tenants:false → sign up from .secrets.env (generated on
#                                 first run), verify login, print project key
#   /api/signup → tenants:true  → nothing to create; verify the stored
#                                 credentials still log in (warn, don't fail)
#
# The signup route itself was read from the running chalice container
# (routers/core_dynamic.py): POST /api/signup with
# {email, password, fullname, organizationName}, answered with a jwt on
# success or {"errors":[…]} on refusal. The POST route is only REGISTERED
# while no tenant exists at chalice boot, which is why this script always
# checks the GET first and never posts blind.
#
# Usage: signup.sh            (idempotent — safe to re-run any time)
# Env:   OPENREPLAY_SIGNUP_WAIT   seconds to wait for /api/signup (default 300)
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/lib.sh"

WAIT="${OPENREPLAY_SIGNUP_WAIT:-300}"

# ── secrets: load, or mint on first run ────────────────────────────────────
# Same convention as .devcontainer/post-create.sh's secrets.yaml: a gitignored
# file, generated with openssl on first run, never committed. Explicitly set
# OPENREPLAY_* environment variables win over the file (load_secrets only
# fills variables that are unset).
load_secrets
if [ -z "${OPENREPLAY_EMAIL:-}" ] || [ -z "${OPENREPLAY_PASSWORD:-}" ]; then
  OPENREPLAY_EMAIL="${OPENREPLAY_EMAIL:-admin@example.com}"
  OPENREPLAY_PASSWORD="${OPENREPLAY_PASSWORD:-$(openssl rand -hex 16)}"
  OPENREPLAY_FULLNAME="${OPENREPLAY_FULLNAME:-Hackagon Debug Admin}"
  OPENREPLAY_ORG="${OPENREPLAY_ORG:-Hackagon}"

  # A password is about to be written to disk — make sure git can never take
  # it. On the sketch branches all of .claude/ is ignored; on feat/claude the
  # skill is TRACKED and only the skill's own .gitignore protects this file.
  if command -v git >/dev/null 2>&1 &&
     git -C "$SKILL_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1 &&
     ! git -C "$SKILL_DIR" check-ignore -q "$SECRETS_FILE"; then
    echo "error: $SECRETS_FILE would be TRACKED by git — refusing to write a password there." >&2
    echo "       Add '.secrets.env' to $SKILL_DIR/.gitignore first." >&2
    exit 1
  fi

  umask 077
  cat > "$SECRETS_FILE" <<EOF
# OpenReplay admin credentials — generated by scripts/signup.sh, gitignored.
# KEY=value, no quotes; everything after the first '=' is the value.
# Survives down.sh. After down.sh --volumes (volumes wiped, signup reopens)
# the next up.sh re-creates the same account from these values.
OPENREPLAY_EMAIL=$OPENREPLAY_EMAIL
OPENREPLAY_PASSWORD=$OPENREPLAY_PASSWORD
OPENREPLAY_FULLNAME=$OPENREPLAY_FULLNAME
OPENREPLAY_ORG=$OPENREPLAY_ORG
EOF
  echo "==> generated admin credentials in $SECRETS_FILE"
  echo "    email     $OPENREPLAY_EMAIL"
  echo "    password  $OPENREPLAY_PASSWORD"
  echo "    ⚠ shown this once — afterwards, read the file."
fi
OPENREPLAY_FULLNAME="${OPENREPLAY_FULLNAME:-Hackagon Debug Admin}"
OPENREPLAY_ORG="${OPENREPLAY_ORG:-Hackagon}"

# ── wait for the API, read the tenants flag ────────────────────────────────
url="$(cat "$STATE/tunnel-url" 2>/dev/null || true)"
[ -n "$url" ] || url="$(tunnel_url || true)"
[ -n "$url" ] || { echo "error: no tunnel URL — is the stack up? (scripts/up.sh)" >&2; exit 1; }

body=""
deadline=$(( $(date +%s) + WAIT ))
while :; do
  body="$(curl -fsS -m 10 "$url/api/signup" 2>/dev/null || true)"
  case "$body" in *'"tenants"'*) break ;; esac
  if [ "$(date +%s)" -ge "$deadline" ]; then
    echo "error: $url/api/signup did not answer within ${WAIT}s" >&2
    echo "       (first run pulls images + migrates — re-run: bash $HERE/signup.sh)" >&2
    exit 1
  fi
  sleep 5
done

login_jwt() { # stdout: jwt, empty on failure
  curl -fsS -m 30 -X POST "$url/api/login" -H 'Content-Type: application/json' \
    -d "{\"email\":\"$OPENREPLAY_EMAIL\",\"password\":\"$OPENREPLAY_PASSWORD\"}" 2>/dev/null |
    sed -n 's/.*"jwt":"\([^"]*\)".*/\1/p'
}

# ── tenant exists: nothing to create, just prove the stored creds work ─────
case "$body" in
  *'"tenants": true'* | *'"tenants":true'*)
    echo "==> OpenReplay admin account already exists — skipping signup"
    jwt="$(login_jwt)"
    if [ -z "$jwt" ]; then
      echo "    ⚠ the stored credentials ($OPENREPLAY_EMAIL) do NOT log in." >&2
      echo "      The account was created some other way. Either fix $SECRETS_FILE" >&2
      echo "      to match it, or start over: down.sh --volumes && up.sh" >&2
      exit 0   # an existing account must never fail a bring-up
    fi
    ;;
  *)
    # ── no tenant: sign up ─────────────────────────────────────────────────
    echo "==> creating the OpenReplay admin account ($OPENREPLAY_EMAIL)…"
    resp="$(curl -fsS -m 30 -X POST "$url/api/signup" -H 'Content-Type: application/json' \
      -d "{\"email\":\"$OPENREPLAY_EMAIL\",\"password\":\"$OPENREPLAY_PASSWORD\",\"fullname\":\"$OPENREPLAY_FULLNAME\",\"organizationName\":\"$OPENREPLAY_ORG\"}")"
    case "$resp" in
      *'"errors"'*)
        echo "error: signup refused: $resp" >&2
        exit 1 ;;
      *'"jwt"'*) ;;
      *)
        echo "error: unexpected signup response: ${resp:0:200}" >&2
        exit 1 ;;
    esac
    # Authenticate FROM THE FILE, not with the jwt signup returned — this is
    # the round trip the owner will actually need later.
    jwt="$(login_jwt)"
    [ -n "$jwt" ] || { echo "error: signup succeeded but login with the stored credentials failed" >&2; exit 1; }
    echo "    account created and login verified"
    ;;
esac

# ── project key (signup auto-creates "my first project") ───────────────────
key="$(curl -fsS -m 30 "$url/api/projects" -H "Authorization: Bearer $jwt" 2>/dev/null |
  sed -n 's/.*"projectKey":"\([^"]*\)".*/\1/p' | head -1)"

echo ""
echo "  admin       $OPENREPLAY_EMAIL   (password: see $SECRETS_FILE)"
if [ -n "$key" ]; then
  echo "  projectKey  $key"
  echo "  wire-frontend.sh reads these credentials itself — no env vars needed."
else
  echo "  ⚠ no project key found — check $url/api/projects in the UI" >&2
fi
