// Code generated by ent, DO NOT EDIT.

package page

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the page type in the database.
	Label = "page"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldVisible holds the string denoting the visible field in the database.
	FieldVisible = "visible"
	// FieldOrder holds the string denoting the order field in the database.
	FieldOrder = "order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldModifiedAt holds the string denoting the modified_at field in the database.
	FieldModifiedAt = "modified_at"
	// EdgeHackathon holds the string denoting the hackathon edge name in mutations.
	EdgeHackathon = "hackathon"
	// EdgePhase holds the string denoting the phase edge name in mutations.
	EdgePhase = "phase"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeModifier holds the string denoting the modifier edge name in mutations.
	EdgeModifier = "modifier"
	// Table holds the table name of the page in the database.
	Table = "pages"
	// HackathonTable is the table that holds the hackathon relation/edge.
	HackathonTable = "pages"
	// HackathonInverseTable is the table name for the Hackathon entity.
	// It exists in this package in order to avoid circular dependency with the "hackathon" package.
	HackathonInverseTable = "hackathons"
	// HackathonColumn is the table column denoting the hackathon relation/edge.
	HackathonColumn = "hackathon_pages"
	// PhaseTable is the table that holds the phase relation/edge.
	PhaseTable = "pages"
	// PhaseInverseTable is the table name for the Phase entity.
	// It exists in this package in order to avoid circular dependency with the "phase" package.
	PhaseInverseTable = "phases"
	// PhaseColumn is the table column denoting the phase relation/edge.
	PhaseColumn = "phase_page"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "pages"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "user_created_pages"
	// ModifierTable is the table that holds the modifier relation/edge.
	ModifierTable = "pages"
	// ModifierInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ModifierInverseTable = "users"
	// ModifierColumn is the table column denoting the modifier relation/edge.
	ModifierColumn = "user_modified_pages"
)

// Columns holds all SQL columns for page fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldContent,
	FieldVisible,
	FieldOrder,
	FieldCreatedAt,
	FieldModifiedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "pages"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"hackathon_pages",
	"phase_page",
	"user_created_pages",
	"user_modified_pages",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultVisible holds the default value on creation for the "visible" field.
	DefaultVisible bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultModifiedAt holds the default value on creation for the "modified_at" field.
	DefaultModifiedAt func() time.Time
	// UpdateDefaultModifiedAt holds the default value on update for the "modified_at" field.
	UpdateDefaultModifiedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Page queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByVisible orders the results by the visible field.
func ByVisible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisible, opts...).ToFunc()
}

// ByOrder orders the results by the order field.
func ByOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByModifiedAt orders the results by the modified_at field.
func ByModifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModifiedAt, opts...).ToFunc()
}

// ByHackathonField orders the results by hackathon field.
func ByHackathonField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHackathonStep(), sql.OrderByField(field, opts...))
	}
}

// ByPhaseField orders the results by phase field.
func ByPhaseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPhaseStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByModifierField orders the results by modifier field.
func ByModifierField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModifierStep(), sql.OrderByField(field, opts...))
	}
}
func newHackathonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HackathonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HackathonTable, HackathonColumn),
	)
}
func newPhaseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhaseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, PhaseTable, PhaseColumn),
	)
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newModifierStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModifierInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModifierTable, ModifierColumn),
	)
}
