// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hackathon/messages/track_svc/edit_request.proto

package track_svc

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditRequest) Reset() {
	*x = EditRequest{}
	mi := &file_hackathon_messages_track_svc_edit_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRequest) ProtoMessage() {}

func (x *EditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hackathon_messages_track_svc_edit_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRequest.ProtoReflect.Descriptor instead.
func (*EditRequest) Descriptor() ([]byte, []int) {
	return file_hackathon_messages_track_svc_edit_request_proto_rawDescGZIP(), []int{0}
}

func (x *EditRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *EditRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EditRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

var File_hackathon_messages_track_svc_edit_request_proto protoreflect.FileDescriptor

const file_hackathon_messages_track_svc_edit_request_proto_rawDesc = "" +
	"\n" +
	"/hackathon/messages/track_svc/edit_request.proto\x12\x1chackathon.messages.track_svc\x1a\x1bbuf/validate/validate.proto\"\xa3\x01\n" +
	"\vEditRequest\x12#\n" +
	"\btrack_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\atrackId\x12#\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x03\x18\xff\x01H\x00R\x04name\x88\x01\x01\x121\n" +
	"\vdescription\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x03\x18\x90NH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionBkZigithub.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/messages/track_svcb\x06proto3"

var (
	file_hackathon_messages_track_svc_edit_request_proto_rawDescOnce sync.Once
	file_hackathon_messages_track_svc_edit_request_proto_rawDescData []byte
)

func file_hackathon_messages_track_svc_edit_request_proto_rawDescGZIP() []byte {
	file_hackathon_messages_track_svc_edit_request_proto_rawDescOnce.Do(func() {
		file_hackathon_messages_track_svc_edit_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hackathon_messages_track_svc_edit_request_proto_rawDesc), len(file_hackathon_messages_track_svc_edit_request_proto_rawDesc)))
	})
	return file_hackathon_messages_track_svc_edit_request_proto_rawDescData
}

var file_hackathon_messages_track_svc_edit_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hackathon_messages_track_svc_edit_request_proto_goTypes = []any{
	(*EditRequest)(nil), // 0: hackathon.messages.track_svc.EditRequest
}
var file_hackathon_messages_track_svc_edit_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hackathon_messages_track_svc_edit_request_proto_init() }
func file_hackathon_messages_track_svc_edit_request_proto_init() {
	if File_hackathon_messages_track_svc_edit_request_proto != nil {
		return
	}
	file_hackathon_messages_track_svc_edit_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hackathon_messages_track_svc_edit_request_proto_rawDesc), len(file_hackathon_messages_track_svc_edit_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hackathon_messages_track_svc_edit_request_proto_goTypes,
		DependencyIndexes: file_hackathon_messages_track_svc_edit_request_proto_depIdxs,
		MessageInfos:      file_hackathon_messages_track_svc_edit_request_proto_msgTypes,
	}.Build()
	File_hackathon_messages_track_svc_edit_request_proto = out.File
	file_hackathon_messages_track_svc_edit_request_proto_goTypes = nil
	file_hackathon_messages_track_svc_edit_request_proto_depIdxs = nil
}
