syntax = "proto3";

package hackathon;

import "google/protobuf/empty.proto";

import "create_hackathon_request.proto";
import "create_hackathon_response.proto";
import "add_user_request.proto";
import "add_user_response.proto";
import "remove_user_request.proto";
import "add_page_request.proto";
import "add_page_response.proto";
import "delete_page_request.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/proto";

service HackathonSvc {
  rpc Create(CreateHackathonRequest) returns (CreateHackathonResponse);
  rpc AddUser(AddUserRequest) returns (AddUserResponse);
  rpc RemoveUser(RemoveUserRequest) returns (google.protobuf.Empty);
  rpc AddPage(AddPageRequest) returns (AddPageResponse);
  rpc DeletePage(DeletePageRequest) returns (google.protobuf.Empty);
}
