syntax = "proto3";

package user;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/proto";

service User {
  rpc List(UserListRequest) returns (UserListResponse);
  rpc WhoAmI(WhoAmIRequest) returns (WhoAmIResponse);
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc AddRole(AddRoleRequest) returns (AddRoleResponse);
  rpc RemoveRole(RemoveRoleRequest) returns (RemoveRoleResponse);
}

message UserListRequest {}

message UserListResponse {
    repeated UserEntry users = 1;
}

message WhoAmIRequest {}

message WhoAmIResponse {
    UserEntry user = 1;
}

message RegisterRequest {}

message RegisterResponse {
    UserEntry user = 1;
}

message UserEntry {
    string id = 1;
    string name = 2;
    string keycloak_id = 3;
    google.protobuf.Timestamp created_at = 4;
    string display_name = 5;
    string email = 6;
    repeated GlobalRole roles = 7;
}

enum GlobalRole {
    Admin = 0;
    HackathonOrganizer = 1;
}

message AddRoleRequest{
    string user_id = 1;
    GlobalRole role = 2;
}
message AddRoleResponse{
    UserEntry user = 1;
}

message RemoveRoleRequest{
    string user_id = 1;
    GlobalRole role = 2;
}

message RemoveRoleResponse{
    UserEntry user = 1;
}

