syntax = "proto3";

package hackathon;

import "google/protobuf/timestamp.proto";
import "hackathon/entities/visibility.proto";
import "hackathon/entities/hackathon_member.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto";

message Hackathon {
    string id = 1;
    string name = 2;
    optional google.protobuf.Timestamp start_date = 3;
    optional google.protobuf.Timestamp end_date = 4;
    google.protobuf.Timestamp created_at = 5;
    google.protobuf.Timestamp modified_at = 6;
    Visibility visibility = 7;
    optional string description = 8;
    optional string logo = 9;
    repeated HackathonMember members = 10;
}
