syntax = "proto3";

package hackathon.entities;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/entities";

message Phase {
  string id = 1;
  string name = 2;
  optional string description = 3;
  optional google.protobuf.Timestamp starts_at = 4;
  optional google.protobuf.Timestamp ends_at = 5;

  option (buf.validate.message).cel = {
    id: "starts_at_requires_ends_at"
    message: "ends_at must be present if starts_at is present and must be after starts_at"
    expression: "(!has(this.starts_at) && !has(this.ends_at)) || (has(this.starts_at) && has(this.ends_at) && this.ends_at >= this.starts_at)"
  };

  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp modified_at = 7;
  string hackathon_id = 8;
  optional string page_id = 9;
  string creator_id = 10;
  string modifier_id = 11;
  PhaseType phase_type = 12;
}

enum PhaseType {
  PHASE_TYPE_UNSPECIFIED = 0;
  PHASE_TYPE_VOTING = 1;
  PHASE_TYPE_INFORMATIVE = 2;
}