syntax = "proto3";

package hackathon.entities;

import "google/protobuf/timestamp.proto";
import "hackathon/entities/submission.proto";
import "user/entities/user.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/entities";

message Team {
  string id = 1;
  string name = 2;
  optional string description = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp modified_at = 5;
  string project_id = 6;
  string creator_id = 7;
  optional string modifier_id = 8;
  repeated user.entities.User members = 9;
  repeated Submission submissions = 10;
}
