apiVersion: v1
kind: Service
metadata:
  name: {{ include "hackagon.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hackagon.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "hackagon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend