apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hackagon.fullname" . }}-frontend-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hackagon.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.yaml: |
    oidc:
      clientSecret: {{ .Values.frontendSecrets.clientSecret | required "frontendSecrets.clientSecret is required" | quote }}
      authSecret: {{ .Values.frontendSecrets.authSecret | required "frontendSecrets.authSecret is required" | quote }}