// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hackathon/entities/question.proto

package entities

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionType int32

const (
	QuestionType_QUESTION_TYPE_UNSPECIFIED QuestionType = 0
	QuestionType_QUESTION_TYPE_TEXT        QuestionType = 1
	QuestionType_QUESTION_TYPE_BOOL        QuestionType = 2
	QuestionType_QUESTION_TYPE_ENUM        QuestionType = 3
)

// Enum value maps for QuestionType.
var (
	QuestionType_name = map[int32]string{
		0: "QUESTION_TYPE_UNSPECIFIED",
		1: "QUESTION_TYPE_TEXT",
		2: "QUESTION_TYPE_BOOL",
		3: "QUESTION_TYPE_ENUM",
	}
	QuestionType_value = map[string]int32{
		"QUESTION_TYPE_UNSPECIFIED": 0,
		"QUESTION_TYPE_TEXT":        1,
		"QUESTION_TYPE_BOOL":        2,
		"QUESTION_TYPE_ENUM":        3,
	}
)

func (x QuestionType) Enum() *QuestionType {
	p := new(QuestionType)
	*p = x
	return p
}

func (x QuestionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionType) Descriptor() protoreflect.EnumDescriptor {
	return file_hackathon_entities_question_proto_enumTypes[0].Descriptor()
}

func (QuestionType) Type() protoreflect.EnumType {
	return &file_hackathon_entities_question_proto_enumTypes[0]
}

func (x QuestionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionType.Descriptor instead.
func (QuestionType) EnumDescriptor() ([]byte, []int) {
	return file_hackathon_entities_question_proto_rawDescGZIP(), []int{0}
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Type          QuestionType           `protobuf:"varint,4,opt,name=type,proto3,enum=hackathon.entities.QuestionType" json:"type,omitempty"`
	Mandatory     bool                   `protobuf:"varint,5,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	Order         int32                  `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	Options       []string               `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_hackathon_entities_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_hackathon_entities_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_hackathon_entities_question_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Question) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Question) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *Question) GetMandatory() bool {
	if x != nil {
		return x.Mandatory
	}
	return false
}

func (x *Question) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_hackathon_entities_question_proto protoreflect.FileDescriptor

const file_hackathon_entities_question_proto_rawDesc = "" +
	"\n" +
	"!hackathon/entities/question.proto\x12\x12hackathon.entities\x1a\x1bbuf/validate/validate.proto\"\xea\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x03key\x18\x02 \x01(\tB\x18\xbaH\x15r\x132\x11^[a-z][a-z0-9_]*$R\x03key\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12>\n" +
	"\x04type\x18\x04 \x01(\x0e2 .hackathon.entities.QuestionTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04type\x12\x1c\n" +
	"\tmandatory\x18\x05 \x01(\bR\tmandatory\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\x12\x18\n" +
	"\aoptions\x18\a \x03(\tR\aoptions*u\n" +
	"\fQuestionType\x12\x1d\n" +
	"\x19QUESTION_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12QUESTION_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12QUESTION_TYPE_BOOL\x10\x02\x12\x16\n" +
	"\x12QUESTION_TYPE_ENUM\x10\x03BaZ_github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/entitiesb\x06proto3"

var (
	file_hackathon_entities_question_proto_rawDescOnce sync.Once
	file_hackathon_entities_question_proto_rawDescData []byte
)

func file_hackathon_entities_question_proto_rawDescGZIP() []byte {
	file_hackathon_entities_question_proto_rawDescOnce.Do(func() {
		file_hackathon_entities_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hackathon_entities_question_proto_rawDesc), len(file_hackathon_entities_question_proto_rawDesc)))
	})
	return file_hackathon_entities_question_proto_rawDescData
}

var file_hackathon_entities_question_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hackathon_entities_question_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hackathon_entities_question_proto_goTypes = []any{
	(QuestionType)(0), // 0: hackathon.entities.QuestionType
	(*Question)(nil),  // 1: hackathon.entities.Question
}
var file_hackathon_entities_question_proto_depIdxs = []int32{
	0, // 0: hackathon.entities.Question.type:type_name -> hackathon.entities.QuestionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hackathon_entities_question_proto_init() }
func file_hackathon_entities_question_proto_init() {
	if File_hackathon_entities_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hackathon_entities_question_proto_rawDesc), len(file_hackathon_entities_question_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hackathon_entities_question_proto_goTypes,
		DependencyIndexes: file_hackathon_entities_question_proto_depIdxs,
		EnumInfos:         file_hackathon_entities_question_proto_enumTypes,
		MessageInfos:      file_hackathon_entities_question_proto_msgTypes,
	}.Build()
	File_hackathon_entities_question_proto = out.File
	file_hackathon_entities_question_proto_goTypes = nil
	file_hackathon_entities_question_proto_depIdxs = nil
}
