// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hackathon/entities/submission.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Submission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result        *string                `protobuf:"bytes,2,opt,name=result,proto3,oneof" json:"result,omitempty"`
	Status        SubmissionStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=hackathon.entities.SubmissionStatus" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	TeamId        string                 `protobuf:"bytes,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,8,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CreatorId     string                 `protobuf:"bytes,9,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ModifierId    *string                `protobuf:"bytes,10,opt,name=modifier_id,json=modifierId,proto3,oneof" json:"modifier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_hackathon_entities_submission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_hackathon_entities_submission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_hackathon_entities_submission_proto_rawDescGZIP(), []int{0}
}

func (x *Submission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Submission) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

func (x *Submission) GetStatus() SubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SubmissionStatus_SUBMISSION_STATUS_UNSPECIFIED
}

func (x *Submission) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Submission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Submission) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *Submission) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Submission) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Submission) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *Submission) GetModifierId() string {
	if x != nil && x.ModifierId != nil {
		return *x.ModifierId
	}
	return ""
}

var File_hackathon_entities_submission_proto protoreflect.FileDescriptor

const file_hackathon_entities_submission_proto_rawDesc = "" +
	"\n" +
	"#hackathon/entities/submission.proto\x12\x12hackathon.entities\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*hackathon/entities/submission_status.proto\"\xa1\x03\n" +
	"\n" +
	"Submission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x06result\x18\x02 \x01(\tH\x00R\x06result\x88\x01\x01\x12<\n" +
	"\x06status\x18\x03 \x01(\x0e2$.hackathon.entities.SubmissionStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x17\n" +
	"\ateam_id\x18\a \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"project_id\x18\b \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\t \x01(\tR\tcreatorId\x12$\n" +
	"\vmodifier_id\x18\n" +
	" \x01(\tH\x01R\n" +
	"modifierId\x88\x01\x01B\t\n" +
	"\a_resultB\x0e\n" +
	"\f_modifier_idBaZ_github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/hackathon/entitiesb\x06proto3"

var (
	file_hackathon_entities_submission_proto_rawDescOnce sync.Once
	file_hackathon_entities_submission_proto_rawDescData []byte
)

func file_hackathon_entities_submission_proto_rawDescGZIP() []byte {
	file_hackathon_entities_submission_proto_rawDescOnce.Do(func() {
		file_hackathon_entities_submission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hackathon_entities_submission_proto_rawDesc), len(file_hackathon_entities_submission_proto_rawDesc)))
	})
	return file_hackathon_entities_submission_proto_rawDescData
}

var file_hackathon_entities_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hackathon_entities_submission_proto_goTypes = []any{
	(*Submission)(nil),            // 0: hackathon.entities.Submission
	(SubmissionStatus)(0),         // 1: hackathon.entities.SubmissionStatus
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_hackathon_entities_submission_proto_depIdxs = []int32{
	1, // 0: hackathon.entities.Submission.status:type_name -> hackathon.entities.SubmissionStatus
	2, // 1: hackathon.entities.Submission.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: hackathon.entities.Submission.modified_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hackathon_entities_submission_proto_init() }
func file_hackathon_entities_submission_proto_init() {
	if File_hackathon_entities_submission_proto != nil {
		return
	}
	file_hackathon_entities_submission_status_proto_init()
	file_hackathon_entities_submission_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hackathon_entities_submission_proto_rawDesc), len(file_hackathon_entities_submission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hackathon_entities_submission_proto_goTypes,
		DependencyIndexes: file_hackathon_entities_submission_proto_depIdxs,
		MessageInfos:      file_hackathon_entities_submission_proto_msgTypes,
	}.Build()
	File_hackathon_entities_submission_proto = out.File
	file_hackathon_entities_submission_proto_goTypes = nil
	file_hackathon_entities_submission_proto_depIdxs = nil
}
