syntax = "proto3";

package user;

import "user/messages/user_svc/add_role_request.proto";
import "user/messages/user_svc/add_role_response.proto";
import "user/messages/user_svc/get_request.proto";
import "user/messages/user_svc/get_response.proto";
import "user/messages/user_svc/list_request.proto";
import "user/messages/user_svc/list_response.proto";
import "user/messages/user_svc/register_request.proto";
import "user/messages/user_svc/register_response.proto";
import "user/messages/user_svc/remove_role_request.proto";
import "user/messages/user_svc/remove_role_response.proto";
import "user/messages/user_svc/who_am_i_request.proto";
import "user/messages/user_svc/who_am_i_response.proto";

option go_package = "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/user";

service UserService {
  rpc List(user.messages.user_svc.ListRequest) returns (user.messages.user_svc.ListResponse);
  rpc Get(user.messages.user_svc.GetRequest) returns (user.messages.user_svc.GetResponse);
  rpc WhoAmI(user.messages.user_svc.WhoAmIRequest) returns (user.messages.user_svc.WhoAmIResponse);
  rpc Register(user.messages.user_svc.RegisterRequest) returns (user.messages.user_svc.RegisterResponse);
  rpc AddRole(user.messages.user_svc.AddRoleRequest) returns (user.messages.user_svc.AddRoleResponse);
  rpc RemoveRole(user.messages.user_svc.RemoveRoleRequest) returns (user.messages.user_svc.RemoveRoleResponse);
}
