# shellcheck shell=bash
# Shared helpers. Source after setting HERE.

SKILL_DIR="$(dirname "$HERE")"
VENDOR="$SKILL_DIR/vendor"
STATE="$SKILL_DIR/.state"
PROJECT="${PLAUSIBLE_PROJECT:-plausible}"
# Pin upstream. The CE compose is a versioned artefact: the image tag inside it
# is the release, so the ref and the running version are one decision.
UPSTREAM_REPO="${PLAUSIBLE_REPO:-https://github.com/plausible/community-edition.git}"
UPSTREAM_REF="${PLAUSIBLE_REF:-v3.2.1}"

# The port `plausible` is published on, on the LOOPBACK interface only. The
# tunnel is the entrypoint (the browser has to reach the ingest endpoint from
# outside), but a local port is what lets doctor/verify tell "the app is broken"
# apart from "the tunnel is broken" — two failures that look identical from the
# public URL.
#
# 8010, not upstream's 8000: 8000 is the single most contested port on a
# developer machine (it was already taken by an unrelated python process on the
# machine this was built on) and a collision here fails `compose up` AFTER the
# databases have started, which reads as a stack failure rather than a clash.
# The container still listens on 8000 inside; only the host side moves.
LOCAL_PORT="${PLAUSIBLE_PORT:-8010}"

mkdir -p "$STATE"

# Admin credentials + SECRET_KEY_BASE — generated by scripts/secrets.sh on
# first run, gitignored (skill .gitignore; also ignored repo-wide).
#
# OUTSIDE .state on purpose, exactly as in openreplay-stack: the password must
# survive down.sh, and surviving `--volumes` is what makes a wipe a RECOVERY
# path rather than a second loss — the next up.sh re-creates the same account
# from this file.
SECRETS_FILE="$SKILL_DIR/.secrets.env"

# Fill unset PLAUSIBLE_* variables from the secrets file. Explicit environment
# wins — an exported PLAUSIBLE_PASSWORD is someone overriding on purpose.
# Plain KEY=value lines, no quoting: the value is everything after the first
# '=', so spaces survive without shell-quoting rules getting involved.
#
# ⚠ THE `\r` STRIP IS LOad-BEARING ON WINDOWS, and it cost an hour. Git Bash's
# openssl (/mingw64/bin/openssl) prints CRLF, so a naively captured
# `openssl rand -base64 32` ends in a carriage return. That CR then rides
# inside the VALUE — not at the end of the line, where every tool would treat
# it as a line ending — and Plausible dies at boot with
# `TOTP_VAULT_KEY must be Base64 encoded 32 bytes`, an error about a key that
# decodes to exactly 32 bytes everywhere you check it.
#
# It survives every obvious check: `cat -A` on a file sed has since rewritten
# shows nothing (MSYS sed strips CRs on the way through), `docker compose
# config` shows it clean because that reads .env rather than the process
# environment, and `docker inspect --format '{{range .Config.Env}}'` renders
# the CR as the line break it looks like. Only `{{json .Config.Env}}` shows it.
# Stripped here as well as at the point of generation, because a .secrets.env
# already on disk is not fixed by fixing the generator.
load_secrets() {
  [ -f "$SECRETS_FILE" ] || return 0
  local line k v
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%$'\r'}"
    case "$line" in '' | \#*) continue ;; esac
    k="${line%%=*}"
    case "$k" in *[!A-Za-z0-9_]* | '') continue ;; esac
    v="${line#*=}"
    v="${v%$'\r'}"
    [ -n "${!k:-}" ] || export "$k=$v"
  done <"$SECRETS_FILE"
}

# Paths handed to docker.exe. On Git Bash/MSYS, MSYS_NO_PATHCONV stops the
# automatic POSIX→Windows translation (needed so docker's own /container/paths
# survive), which means a `/c/Users/...` argument reaches docker.exe verbatim
# and it resolves `C:\c\Users\...`. Hand it a Windows-style path instead;
# MSYS leaves those alone. Same fix as openreplay-stack/scripts/lib.sh.
COMPOSE_VENDOR="$VENDOR/compose.yml"
COMPOSE_OVERLAY="$SKILL_DIR/compose.tunnel.yaml"
COMPOSE_DIR="$VENDOR"
case "$(uname -s)" in
  MINGW* | MSYS*)
    export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL="*"
    COMPOSE_VENDOR="$(cygpath -m "$COMPOSE_VENDOR")"
    COMPOSE_OVERLAY="$(cygpath -m "$COMPOSE_OVERLAY")"
    COMPOSE_DIR="$(cygpath -m "$COMPOSE_DIR")"
    ;;
esac

# `--project-directory vendor` matters twice: upstream's compose bind-mounts
# ./clickhouse/*.xml relative to it, and compose reads `.env` from it — which
# is the file up.sh writes BASE_URL and the secrets into.
# Where curl should throw a body away.
#
# NOT `/dev/null` on a Windows host: this file exports MSYS_NO_PATHCONV=1 for
# docker's sake, so `/dev/null` reaches curl.exe verbatim, curl tries to create
# a file at that literal path, and fails with
# `curl: (23) client returned ERROR on write of 72 bytes` — printed in the
# middle of a check that then passes anyway, because `-w '%{http_code}'` has
# already produced the number the caller wanted. A scary line attached to a
# successful step is worse than either a failure or silence.
CURL_DISCARD="/dev/null"
case "$(uname -s)" in
  MINGW* | MSYS*) CURL_DISCARD="NUL" ;;
esac

compose() {
  docker compose -p "$PROJECT" \
    -f "$COMPOSE_VENDOR" -f "$COMPOSE_OVERLAY" \
    --project-directory "$COMPOSE_DIR" "$@"
}

require_docker() {
  command -v docker >/dev/null 2>&1 || {
    echo "error: docker not found" >&2
    exit 1
  }
  docker info >/dev/null 2>&1 || {
    echo "error: docker daemon not reachable" >&2
    exit 1
  }
}

require_vendor() {
  [ -f "$VENDOR/compose.yml" ] || {
    echo "error: upstream not fetched — run scripts/fetch-upstream.sh" >&2
    exit 1
  }
}

ENV_FILE="$VENDOR/.env"

# Idempotent `KEY=value` in vendor/.env. Compose reads that file for ${VAR}
# interpolation AND for the bare `- TOTP_VAULT_KEY` style pass-throughs in
# upstream's compose, so it is the one place configuration lives.
env_set() { # <key> <value>
  mkdir -p "$VENDOR"
  touch "$ENV_FILE"
  # Same CR strip as load_secrets, for the same reason and one layer further
  # out: whatever the value came from, a CR must not reach a container.
  set -- "$1" "${2%$'\r'}"
  if grep -q "^$1=" "$ENV_FILE"; then
    # `|` as the sed delimiter: values here are URLs, and base64 secrets can
    # contain `/`.
    sed -i "s|^$1=.*|$1=$2|" "$ENV_FILE"
  else
    printf '%s=%s\n' "$1" "$2" >>"$ENV_FILE"
  fi
}

# Write one KEY=value into .secrets.env, replacing any existing line.
#
# It exists for the API key, and the reason is the recovery story: after
# `down.sh --volumes` the databases are gone but this FILE survives on purpose,
# so a stored key names a row that no longer exists. Appending a second line
# would leave load_secrets reading whichever came first — so this replaces.
secrets_set() { # <key> <value>
  local k="$1" v="${2%$'\r'}"
  if command -v git >/dev/null 2>&1 &&
    git -C "$SKILL_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1 &&
    ! git -C "$SKILL_DIR" check-ignore -q "$SECRETS_FILE"; then
    echo "error: $SECRETS_FILE is not gitignored — refusing to write a secret there." >&2
    return 1
  fi
  umask 077
  touch "$SECRETS_FILE"
  if grep -q "^$k=" "$SECRETS_FILE"; then
    sed -i "s|^$k=.*|$k=$v|" "$SECRETS_FILE"
  else
    printf '%s=%s\n' "$k" "$v" >>"$SECRETS_FILE"
  fi
  export "$k=$v"
}

env_get() { # <key> -> stdout (empty when absent)
  [ -f "$ENV_FILE" ] || return 0
  sed -n "s|^$1=||p" "$ENV_FILE" | tail -1
}

# Read the quick-tunnel URL out of cloudflared's log (it only ever prints it
# there). The state file is the cache; the log is the truth, because a tunnel
# that was restarted has a different URL and the same state file.
tunnel_url() {
  docker logs "$(compose ps -q tunnel 2>/dev/null)" 2>&1 |
    grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' | tail -1
}

# The URL to talk to Plausible on from THIS machine. Prefer the loopback port:
# it is the same server, one hop shorter, and it keeps a diagnostic from
# depending on Cloudflare being up. Callers that specifically mean to test the
# public path use tunnel_url.
local_url() { echo "http://127.0.0.1:$LOCAL_PORT"; }
