// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: health/health_service.proto

package health

import (
	health_svc "github.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/health/messages/health_svc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_health_health_service_proto protoreflect.FileDescriptor

const file_health_health_service_proto_rawDesc = "" +
	"\n" +
	"\x1bhealth/health_service.proto\x12\x06health\x1a.health/messages/health_svc/check_request.proto\x1a/health/messages/health_svc/check_response.proto2m\n" +
	"\rHealthService\x12\\\n" +
	"\x05Check\x12(.health.messages.health_svc.CheckRequest\x1a).health.messages.health_svc.CheckResponseBUZSgithub.com/swissdatasciencecenter/hackagon/components/backend/internal/proto/healthb\x06proto3"

var file_health_health_service_proto_goTypes = []any{
	(*health_svc.CheckRequest)(nil),  // 0: health.messages.health_svc.CheckRequest
	(*health_svc.CheckResponse)(nil), // 1: health.messages.health_svc.CheckResponse
}
var file_health_health_service_proto_depIdxs = []int32{
	0, // 0: health.HealthService.Check:input_type -> health.messages.health_svc.CheckRequest
	1, // 1: health.HealthService.Check:output_type -> health.messages.health_svc.CheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_health_health_service_proto_init() }
func file_health_health_service_proto_init() {
	if File_health_health_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_health_service_proto_rawDesc), len(file_health_health_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_health_service_proto_goTypes,
		DependencyIndexes: file_health_health_service_proto_depIdxs,
	}.Build()
	File_health_health_service_proto = out.File
	file_health_health_service_proto_goTypes = nil
	file_health_health_service_proto_depIdxs = nil
}
