// Code generated by ent, DO NOT EDIT.

package votecategory

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the votecategory type in the database.
	Label = "vote_category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldVotingMethod holds the string denoting the voting_method field in the database.
	FieldVotingMethod = "voting_method"
	// FieldVoterType holds the string denoting the voter_type field in the database.
	FieldVoterType = "voter_type"
	// FieldMaxPoints holds the string denoting the max_points field in the database.
	FieldMaxPoints = "max_points"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldModifiedAt holds the string denoting the modified_at field in the database.
	FieldModifiedAt = "modified_at"
	// EdgeHackathon holds the string denoting the hackathon edge name in mutations.
	EdgeHackathon = "hackathon"
	// EdgeJuryMembers holds the string denoting the jury_members edge name in mutations.
	EdgeJuryMembers = "jury_members"
	// EdgeVotes holds the string denoting the votes edge name in mutations.
	EdgeVotes = "votes"
	// EdgeResults holds the string denoting the results edge name in mutations.
	EdgeResults = "results"
	// Table holds the table name of the votecategory in the database.
	Table = "vote_categories"
	// HackathonTable is the table that holds the hackathon relation/edge.
	HackathonTable = "vote_categories"
	// HackathonInverseTable is the table name for the Hackathon entity.
	// It exists in this package in order to avoid circular dependency with the "hackathon" package.
	HackathonInverseTable = "hackathons"
	// HackathonColumn is the table column denoting the hackathon relation/edge.
	HackathonColumn = "hackathon_vote_categories"
	// JuryMembersTable is the table that holds the jury_members relation/edge. The primary key declared below.
	JuryMembersTable = "user_jury_categories"
	// JuryMembersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	JuryMembersInverseTable = "users"
	// VotesTable is the table that holds the votes relation/edge.
	VotesTable = "votes"
	// VotesInverseTable is the table name for the Vote entity.
	// It exists in this package in order to avoid circular dependency with the "vote" package.
	VotesInverseTable = "votes"
	// VotesColumn is the table column denoting the votes relation/edge.
	VotesColumn = "vote_category_votes"
	// ResultsTable is the table that holds the results relation/edge.
	ResultsTable = "vote_results"
	// ResultsInverseTable is the table name for the VoteResult entity.
	// It exists in this package in order to avoid circular dependency with the "voteresult" package.
	ResultsInverseTable = "vote_results"
	// ResultsColumn is the table column denoting the results relation/edge.
	ResultsColumn = "vote_category_results"
)

// Columns holds all SQL columns for votecategory fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldVotingMethod,
	FieldVoterType,
	FieldMaxPoints,
	FieldCreatedAt,
	FieldModifiedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "vote_categories"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"hackathon_vote_categories",
}

var (
	// JuryMembersPrimaryKey and JuryMembersColumn2 are the table columns denoting the
	// primary key for the jury_members relation (M2M).
	JuryMembersPrimaryKey = []string{"user_id", "vote_category_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultModifiedAt holds the default value on creation for the "modified_at" field.
	DefaultModifiedAt func() time.Time
	// UpdateDefaultModifiedAt holds the default value on update for the "modified_at" field.
	UpdateDefaultModifiedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// VotingMethod defines the type for the "voting_method" enum field.
type VotingMethod string

// VotingMethod values.
const (
	VotingMethodSingleChoice VotingMethod = "single_choice"
	VotingMethodRanked       VotingMethod = "ranked"
	VotingMethodPoints       VotingMethod = "points"
)

func (vm VotingMethod) String() string {
	return string(vm)
}

// VotingMethodValidator is a validator for the "voting_method" field enum values. It is called by the builders before save.
func VotingMethodValidator(vm VotingMethod) error {
	switch vm {
	case VotingMethodSingleChoice, VotingMethodRanked, VotingMethodPoints:
		return nil
	default:
		return fmt.Errorf("votecategory: invalid enum value for voting_method field: %q", vm)
	}
}

// VoterType defines the type for the "voter_type" enum field.
type VoterType string

// VoterType values.
const (
	VoterTypeAllParticipants VoterType = "all_participants"
	VoterTypeJury            VoterType = "jury"
)

func (vt VoterType) String() string {
	return string(vt)
}

// VoterTypeValidator is a validator for the "voter_type" field enum values. It is called by the builders before save.
func VoterTypeValidator(vt VoterType) error {
	switch vt {
	case VoterTypeAllParticipants, VoterTypeJury:
		return nil
	default:
		return fmt.Errorf("votecategory: invalid enum value for voter_type field: %q", vt)
	}
}

// OrderOption defines the ordering options for the VoteCategory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByVotingMethod orders the results by the voting_method field.
func ByVotingMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVotingMethod, opts...).ToFunc()
}

// ByVoterType orders the results by the voter_type field.
func ByVoterType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoterType, opts...).ToFunc()
}

// ByMaxPoints orders the results by the max_points field.
func ByMaxPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxPoints, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByModifiedAt orders the results by the modified_at field.
func ByModifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModifiedAt, opts...).ToFunc()
}

// ByHackathonField orders the results by hackathon field.
func ByHackathonField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHackathonStep(), sql.OrderByField(field, opts...))
	}
}

// ByJuryMembersCount orders the results by jury_members count.
func ByJuryMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJuryMembersStep(), opts...)
	}
}

// ByJuryMembers orders the results by jury_members terms.
func ByJuryMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJuryMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVotesCount orders the results by votes count.
func ByVotesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVotesStep(), opts...)
	}
}

// ByVotes orders the results by votes terms.
func ByVotes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVotesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByResultsCount orders the results by results count.
func ByResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResultsStep(), opts...)
	}
}

// ByResults orders the results by results terms.
func ByResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newHackathonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HackathonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HackathonTable, HackathonColumn),
	)
}
func newJuryMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JuryMembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, JuryMembersTable, JuryMembersPrimaryKey...),
	)
}
func newVotesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VotesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VotesTable, VotesColumn),
	)
}
func newResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResultsTable, ResultsColumn),
	)
}
