// Code generated by ent, DO NOT EDIT.

package participant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/predicate"
)

// HackathonID applies equality check predicate on the "hackathon_id" field. It's identical to HackathonIDEQ.
func HackathonID(v int) predicate.Participant {
	return predicate.Participant(sql.FieldEQ(FieldHackathonID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.Participant {
	return predicate.Participant(sql.FieldEQ(FieldUserID, v))
}

// IsWaiting applies equality check predicate on the "is_waiting" field. It's identical to IsWaitingEQ.
func IsWaiting(v bool) predicate.Participant {
	return predicate.Participant(sql.FieldEQ(FieldIsWaiting, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldEQ(FieldCreatedAt, v))
}

// HackathonIDEQ applies the EQ predicate on the "hackathon_id" field.
func HackathonIDEQ(v int) predicate.Participant {
	return predicate.Participant(sql.FieldEQ(FieldHackathonID, v))
}

// HackathonIDNEQ applies the NEQ predicate on the "hackathon_id" field.
func HackathonIDNEQ(v int) predicate.Participant {
	return predicate.Participant(sql.FieldNEQ(FieldHackathonID, v))
}

// HackathonIDIn applies the In predicate on the "hackathon_id" field.
func HackathonIDIn(vs ...int) predicate.Participant {
	return predicate.Participant(sql.FieldIn(FieldHackathonID, vs...))
}

// HackathonIDNotIn applies the NotIn predicate on the "hackathon_id" field.
func HackathonIDNotIn(vs ...int) predicate.Participant {
	return predicate.Participant(sql.FieldNotIn(FieldHackathonID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.Participant {
	return predicate.Participant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.Participant {
	return predicate.Participant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.Participant {
	return predicate.Participant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.Participant {
	return predicate.Participant(sql.FieldNotIn(FieldUserID, vs...))
}

// IsWaitingEQ applies the EQ predicate on the "is_waiting" field.
func IsWaitingEQ(v bool) predicate.Participant {
	return predicate.Participant(sql.FieldEQ(FieldIsWaiting, v))
}

// IsWaitingNEQ applies the NEQ predicate on the "is_waiting" field.
func IsWaitingNEQ(v bool) predicate.Participant {
	return predicate.Participant(sql.FieldNEQ(FieldIsWaiting, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Participant {
	return predicate.Participant(sql.FieldLTE(FieldCreatedAt, v))
}

// HasHackathon applies the HasEdge predicate on the "hackathon" edge.
func HasHackathon() predicate.Participant {
	return predicate.Participant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, HackathonColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, HackathonTable, HackathonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHackathonWith applies the HasEdge predicate on the "hackathon" edge with a given conditions (other predicates).
func HasHackathonWith(preds ...predicate.Hackathon) predicate.Participant {
	return predicate.Participant(func(s *sql.Selector) {
		step := newHackathonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Participant {
	return predicate.Participant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, UserColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Participant {
	return predicate.Participant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Participant) predicate.Participant {
	return predicate.Participant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Participant) predicate.Participant {
	return predicate.Participant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Participant) predicate.Participant {
	return predicate.Participant(sql.NotPredicates(p))
}
