// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathon"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathonstate"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/phase"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/user"
)

// HackathonStateCreate is the builder for creating a HackathonState entity.
type HackathonStateCreate struct {
	config
	mutation *HackathonStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRegistrationsEnabled sets the "registrations_enabled" field.
func (_c *HackathonStateCreate) SetRegistrationsEnabled(v bool) *HackathonStateCreate {
	_c.mutation.SetRegistrationsEnabled(v)
	return _c
}

// SetNillableRegistrationsEnabled sets the "registrations_enabled" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableRegistrationsEnabled(v *bool) *HackathonStateCreate {
	if v != nil {
		_c.SetRegistrationsEnabled(*v)
	}
	return _c
}

// SetVotingEnabled sets the "voting_enabled" field.
func (_c *HackathonStateCreate) SetVotingEnabled(v bool) *HackathonStateCreate {
	_c.mutation.SetVotingEnabled(v)
	return _c
}

// SetNillableVotingEnabled sets the "voting_enabled" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableVotingEnabled(v *bool) *HackathonStateCreate {
	if v != nil {
		_c.SetVotingEnabled(*v)
	}
	return _c
}

// SetProposeProjectsEnabled sets the "propose_projects_enabled" field.
func (_c *HackathonStateCreate) SetProposeProjectsEnabled(v bool) *HackathonStateCreate {
	_c.mutation.SetProposeProjectsEnabled(v)
	return _c
}

// SetNillableProposeProjectsEnabled sets the "propose_projects_enabled" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableProposeProjectsEnabled(v *bool) *HackathonStateCreate {
	if v != nil {
		_c.SetProposeProjectsEnabled(*v)
	}
	return _c
}

// SetSetTeamPreferencesEnabled sets the "set_team_preferences_enabled" field.
func (_c *HackathonStateCreate) SetSetTeamPreferencesEnabled(v bool) *HackathonStateCreate {
	_c.mutation.SetSetTeamPreferencesEnabled(v)
	return _c
}

// SetNillableSetTeamPreferencesEnabled sets the "set_team_preferences_enabled" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableSetTeamPreferencesEnabled(v *bool) *HackathonStateCreate {
	if v != nil {
		_c.SetSetTeamPreferencesEnabled(*v)
	}
	return _c
}

// SetCreateProjectSubmissionsEnabled sets the "create_project_submissions_enabled" field.
func (_c *HackathonStateCreate) SetCreateProjectSubmissionsEnabled(v bool) *HackathonStateCreate {
	_c.mutation.SetCreateProjectSubmissionsEnabled(v)
	return _c
}

// SetNillableCreateProjectSubmissionsEnabled sets the "create_project_submissions_enabled" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableCreateProjectSubmissionsEnabled(v *bool) *HackathonStateCreate {
	if v != nil {
		_c.SetCreateProjectSubmissionsEnabled(*v)
	}
	return _c
}

// SetViewResultsEnabled sets the "view_results_enabled" field.
func (_c *HackathonStateCreate) SetViewResultsEnabled(v bool) *HackathonStateCreate {
	_c.mutation.SetViewResultsEnabled(v)
	return _c
}

// SetNillableViewResultsEnabled sets the "view_results_enabled" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableViewResultsEnabled(v *bool) *HackathonStateCreate {
	if v != nil {
		_c.SetViewResultsEnabled(*v)
	}
	return _c
}

// SetViewTeamsEnabled sets the "view_teams_enabled" field.
func (_c *HackathonStateCreate) SetViewTeamsEnabled(v bool) *HackathonStateCreate {
	_c.mutation.SetViewTeamsEnabled(v)
	return _c
}

// SetNillableViewTeamsEnabled sets the "view_teams_enabled" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableViewTeamsEnabled(v *bool) *HackathonStateCreate {
	if v != nil {
		_c.SetViewTeamsEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HackathonStateCreate) SetCreatedAt(v time.Time) *HackathonStateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableCreatedAt(v *time.Time) *HackathonStateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetModifiedAt sets the "modified_at" field.
func (_c *HackathonStateCreate) SetModifiedAt(v time.Time) *HackathonStateCreate {
	_c.mutation.SetModifiedAt(v)
	return _c
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableModifiedAt(v *time.Time) *HackathonStateCreate {
	if v != nil {
		_c.SetModifiedAt(*v)
	}
	return _c
}

// SetCurrentPhaseID sets the "current_phase_id" field.
func (_c *HackathonStateCreate) SetCurrentPhaseID(v uuid.UUID) *HackathonStateCreate {
	_c.mutation.SetCurrentPhaseID(v)
	return _c
}

// SetNillableCurrentPhaseID sets the "current_phase_id" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableCurrentPhaseID(v *uuid.UUID) *HackathonStateCreate {
	if v != nil {
		_c.SetCurrentPhaseID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *HackathonStateCreate) SetID(v uuid.UUID) *HackathonStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableID(v *uuid.UUID) *HackathonStateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetHackathonID sets the "hackathon" edge to the Hackathon entity by ID.
func (_c *HackathonStateCreate) SetHackathonID(id uuid.UUID) *HackathonStateCreate {
	_c.mutation.SetHackathonID(id)
	return _c
}

// SetHackathon sets the "hackathon" edge to the Hackathon entity.
func (_c *HackathonStateCreate) SetHackathon(v *Hackathon) *HackathonStateCreate {
	return _c.SetHackathonID(v.ID)
}

// SetModifierID sets the "modifier" edge to the User entity by ID.
func (_c *HackathonStateCreate) SetModifierID(id uuid.UUID) *HackathonStateCreate {
	_c.mutation.SetModifierID(id)
	return _c
}

// SetNillableModifierID sets the "modifier" edge to the User entity by ID if the given value is not nil.
func (_c *HackathonStateCreate) SetNillableModifierID(id *uuid.UUID) *HackathonStateCreate {
	if id != nil {
		_c = _c.SetModifierID(*id)
	}
	return _c
}

// SetModifier sets the "modifier" edge to the User entity.
func (_c *HackathonStateCreate) SetModifier(v *User) *HackathonStateCreate {
	return _c.SetModifierID(v.ID)
}

// SetCurrentPhase sets the "current_phase" edge to the Phase entity.
func (_c *HackathonStateCreate) SetCurrentPhase(v *Phase) *HackathonStateCreate {
	return _c.SetCurrentPhaseID(v.ID)
}

// Mutation returns the HackathonStateMutation object of the builder.
func (_c *HackathonStateCreate) Mutation() *HackathonStateMutation {
	return _c.mutation
}

// Save creates the HackathonState in the database.
func (_c *HackathonStateCreate) Save(ctx context.Context) (*HackathonState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HackathonStateCreate) SaveX(ctx context.Context) *HackathonState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HackathonStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HackathonStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HackathonStateCreate) defaults() {
	if _, ok := _c.mutation.RegistrationsEnabled(); !ok {
		v := hackathonstate.DefaultRegistrationsEnabled
		_c.mutation.SetRegistrationsEnabled(v)
	}
	if _, ok := _c.mutation.VotingEnabled(); !ok {
		v := hackathonstate.DefaultVotingEnabled
		_c.mutation.SetVotingEnabled(v)
	}
	if _, ok := _c.mutation.ProposeProjectsEnabled(); !ok {
		v := hackathonstate.DefaultProposeProjectsEnabled
		_c.mutation.SetProposeProjectsEnabled(v)
	}
	if _, ok := _c.mutation.SetTeamPreferencesEnabled(); !ok {
		v := hackathonstate.DefaultSetTeamPreferencesEnabled
		_c.mutation.SetSetTeamPreferencesEnabled(v)
	}
	if _, ok := _c.mutation.CreateProjectSubmissionsEnabled(); !ok {
		v := hackathonstate.DefaultCreateProjectSubmissionsEnabled
		_c.mutation.SetCreateProjectSubmissionsEnabled(v)
	}
	if _, ok := _c.mutation.ViewResultsEnabled(); !ok {
		v := hackathonstate.DefaultViewResultsEnabled
		_c.mutation.SetViewResultsEnabled(v)
	}
	if _, ok := _c.mutation.ViewTeamsEnabled(); !ok {
		v := hackathonstate.DefaultViewTeamsEnabled
		_c.mutation.SetViewTeamsEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := hackathonstate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		v := hackathonstate.DefaultModifiedAt()
		_c.mutation.SetModifiedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := hackathonstate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HackathonStateCreate) check() error {
	if _, ok := _c.mutation.RegistrationsEnabled(); !ok {
		return &ValidationError{Name: "registrations_enabled", err: errors.New(`ent: missing required field "HackathonState.registrations_enabled"`)}
	}
	if _, ok := _c.mutation.VotingEnabled(); !ok {
		return &ValidationError{Name: "voting_enabled", err: errors.New(`ent: missing required field "HackathonState.voting_enabled"`)}
	}
	if _, ok := _c.mutation.ProposeProjectsEnabled(); !ok {
		return &ValidationError{Name: "propose_projects_enabled", err: errors.New(`ent: missing required field "HackathonState.propose_projects_enabled"`)}
	}
	if _, ok := _c.mutation.SetTeamPreferencesEnabled(); !ok {
		return &ValidationError{Name: "set_team_preferences_enabled", err: errors.New(`ent: missing required field "HackathonState.set_team_preferences_enabled"`)}
	}
	if _, ok := _c.mutation.CreateProjectSubmissionsEnabled(); !ok {
		return &ValidationError{Name: "create_project_submissions_enabled", err: errors.New(`ent: missing required field "HackathonState.create_project_submissions_enabled"`)}
	}
	if _, ok := _c.mutation.ViewResultsEnabled(); !ok {
		return &ValidationError{Name: "view_results_enabled", err: errors.New(`ent: missing required field "HackathonState.view_results_enabled"`)}
	}
	if _, ok := _c.mutation.ViewTeamsEnabled(); !ok {
		return &ValidationError{Name: "view_teams_enabled", err: errors.New(`ent: missing required field "HackathonState.view_teams_enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HackathonState.created_at"`)}
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		return &ValidationError{Name: "modified_at", err: errors.New(`ent: missing required field "HackathonState.modified_at"`)}
	}
	if len(_c.mutation.HackathonIDs()) == 0 {
		return &ValidationError{Name: "hackathon", err: errors.New(`ent: missing required edge "HackathonState.hackathon"`)}
	}
	return nil
}

func (_c *HackathonStateCreate) sqlSave(ctx context.Context) (*HackathonState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HackathonStateCreate) createSpec() (*HackathonState, *sqlgraph.CreateSpec) {
	var (
		_node = &HackathonState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(hackathonstate.Table, sqlgraph.NewFieldSpec(hackathonstate.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RegistrationsEnabled(); ok {
		_spec.SetField(hackathonstate.FieldRegistrationsEnabled, field.TypeBool, value)
		_node.RegistrationsEnabled = value
	}
	if value, ok := _c.mutation.VotingEnabled(); ok {
		_spec.SetField(hackathonstate.FieldVotingEnabled, field.TypeBool, value)
		_node.VotingEnabled = value
	}
	if value, ok := _c.mutation.ProposeProjectsEnabled(); ok {
		_spec.SetField(hackathonstate.FieldProposeProjectsEnabled, field.TypeBool, value)
		_node.ProposeProjectsEnabled = value
	}
	if value, ok := _c.mutation.SetTeamPreferencesEnabled(); ok {
		_spec.SetField(hackathonstate.FieldSetTeamPreferencesEnabled, field.TypeBool, value)
		_node.SetTeamPreferencesEnabled = value
	}
	if value, ok := _c.mutation.CreateProjectSubmissionsEnabled(); ok {
		_spec.SetField(hackathonstate.FieldCreateProjectSubmissionsEnabled, field.TypeBool, value)
		_node.CreateProjectSubmissionsEnabled = value
	}
	if value, ok := _c.mutation.ViewResultsEnabled(); ok {
		_spec.SetField(hackathonstate.FieldViewResultsEnabled, field.TypeBool, value)
		_node.ViewResultsEnabled = value
	}
	if value, ok := _c.mutation.ViewTeamsEnabled(); ok {
		_spec.SetField(hackathonstate.FieldViewTeamsEnabled, field.TypeBool, value)
		_node.ViewTeamsEnabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(hackathonstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ModifiedAt(); ok {
		_spec.SetField(hackathonstate.FieldModifiedAt, field.TypeTime, value)
		_node.ModifiedAt = value
	}
	if nodes := _c.mutation.HackathonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   hackathonstate.HackathonTable,
			Columns: []string{hackathonstate.HackathonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.hackathon_state = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ModifierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   hackathonstate.ModifierTable,
			Columns: []string{hackathonstate.ModifierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_modified_states = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CurrentPhaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   hackathonstate.CurrentPhaseTable,
			Columns: []string{hackathonstate.CurrentPhaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CurrentPhaseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HackathonState.Create().
//		SetRegistrationsEnabled(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HackathonStateUpsert) {
//			SetRegistrationsEnabled(v+v).
//		}).
//		Exec(ctx)
func (_c *HackathonStateCreate) OnConflict(opts ...sql.ConflictOption) *HackathonStateUpsertOne {
	_c.conflict = opts
	return &HackathonStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HackathonState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HackathonStateCreate) OnConflictColumns(columns ...string) *HackathonStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HackathonStateUpsertOne{
		create: _c,
	}
}

type (
	// HackathonStateUpsertOne is the builder for "upsert"-ing
	//  one HackathonState node.
	HackathonStateUpsertOne struct {
		create *HackathonStateCreate
	}

	// HackathonStateUpsert is the "OnConflict" setter.
	HackathonStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetRegistrationsEnabled sets the "registrations_enabled" field.
func (u *HackathonStateUpsert) SetRegistrationsEnabled(v bool) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldRegistrationsEnabled, v)
	return u
}

// UpdateRegistrationsEnabled sets the "registrations_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateRegistrationsEnabled() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldRegistrationsEnabled)
	return u
}

// SetVotingEnabled sets the "voting_enabled" field.
func (u *HackathonStateUpsert) SetVotingEnabled(v bool) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldVotingEnabled, v)
	return u
}

// UpdateVotingEnabled sets the "voting_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateVotingEnabled() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldVotingEnabled)
	return u
}

// SetProposeProjectsEnabled sets the "propose_projects_enabled" field.
func (u *HackathonStateUpsert) SetProposeProjectsEnabled(v bool) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldProposeProjectsEnabled, v)
	return u
}

// UpdateProposeProjectsEnabled sets the "propose_projects_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateProposeProjectsEnabled() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldProposeProjectsEnabled)
	return u
}

// SetSetTeamPreferencesEnabled sets the "set_team_preferences_enabled" field.
func (u *HackathonStateUpsert) SetSetTeamPreferencesEnabled(v bool) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldSetTeamPreferencesEnabled, v)
	return u
}

// UpdateSetTeamPreferencesEnabled sets the "set_team_preferences_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateSetTeamPreferencesEnabled() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldSetTeamPreferencesEnabled)
	return u
}

// SetCreateProjectSubmissionsEnabled sets the "create_project_submissions_enabled" field.
func (u *HackathonStateUpsert) SetCreateProjectSubmissionsEnabled(v bool) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldCreateProjectSubmissionsEnabled, v)
	return u
}

// UpdateCreateProjectSubmissionsEnabled sets the "create_project_submissions_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateCreateProjectSubmissionsEnabled() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldCreateProjectSubmissionsEnabled)
	return u
}

// SetViewResultsEnabled sets the "view_results_enabled" field.
func (u *HackathonStateUpsert) SetViewResultsEnabled(v bool) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldViewResultsEnabled, v)
	return u
}

// UpdateViewResultsEnabled sets the "view_results_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateViewResultsEnabled() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldViewResultsEnabled)
	return u
}

// SetViewTeamsEnabled sets the "view_teams_enabled" field.
func (u *HackathonStateUpsert) SetViewTeamsEnabled(v bool) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldViewTeamsEnabled, v)
	return u
}

// UpdateViewTeamsEnabled sets the "view_teams_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateViewTeamsEnabled() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldViewTeamsEnabled)
	return u
}

// SetModifiedAt sets the "modified_at" field.
func (u *HackathonStateUpsert) SetModifiedAt(v time.Time) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldModifiedAt, v)
	return u
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateModifiedAt() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldModifiedAt)
	return u
}

// SetCurrentPhaseID sets the "current_phase_id" field.
func (u *HackathonStateUpsert) SetCurrentPhaseID(v uuid.UUID) *HackathonStateUpsert {
	u.Set(hackathonstate.FieldCurrentPhaseID, v)
	return u
}

// UpdateCurrentPhaseID sets the "current_phase_id" field to the value that was provided on create.
func (u *HackathonStateUpsert) UpdateCurrentPhaseID() *HackathonStateUpsert {
	u.SetExcluded(hackathonstate.FieldCurrentPhaseID)
	return u
}

// ClearCurrentPhaseID clears the value of the "current_phase_id" field.
func (u *HackathonStateUpsert) ClearCurrentPhaseID() *HackathonStateUpsert {
	u.SetNull(hackathonstate.FieldCurrentPhaseID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.HackathonState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(hackathonstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HackathonStateUpsertOne) UpdateNewValues() *HackathonStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(hackathonstate.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(hackathonstate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HackathonState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HackathonStateUpsertOne) Ignore() *HackathonStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HackathonStateUpsertOne) DoNothing() *HackathonStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HackathonStateCreate.OnConflict
// documentation for more info.
func (u *HackathonStateUpsertOne) Update(set func(*HackathonStateUpsert)) *HackathonStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HackathonStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetRegistrationsEnabled sets the "registrations_enabled" field.
func (u *HackathonStateUpsertOne) SetRegistrationsEnabled(v bool) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetRegistrationsEnabled(v)
	})
}

// UpdateRegistrationsEnabled sets the "registrations_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateRegistrationsEnabled() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateRegistrationsEnabled()
	})
}

// SetVotingEnabled sets the "voting_enabled" field.
func (u *HackathonStateUpsertOne) SetVotingEnabled(v bool) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetVotingEnabled(v)
	})
}

// UpdateVotingEnabled sets the "voting_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateVotingEnabled() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateVotingEnabled()
	})
}

// SetProposeProjectsEnabled sets the "propose_projects_enabled" field.
func (u *HackathonStateUpsertOne) SetProposeProjectsEnabled(v bool) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetProposeProjectsEnabled(v)
	})
}

// UpdateProposeProjectsEnabled sets the "propose_projects_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateProposeProjectsEnabled() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateProposeProjectsEnabled()
	})
}

// SetSetTeamPreferencesEnabled sets the "set_team_preferences_enabled" field.
func (u *HackathonStateUpsertOne) SetSetTeamPreferencesEnabled(v bool) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetSetTeamPreferencesEnabled(v)
	})
}

// UpdateSetTeamPreferencesEnabled sets the "set_team_preferences_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateSetTeamPreferencesEnabled() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateSetTeamPreferencesEnabled()
	})
}

// SetCreateProjectSubmissionsEnabled sets the "create_project_submissions_enabled" field.
func (u *HackathonStateUpsertOne) SetCreateProjectSubmissionsEnabled(v bool) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetCreateProjectSubmissionsEnabled(v)
	})
}

// UpdateCreateProjectSubmissionsEnabled sets the "create_project_submissions_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateCreateProjectSubmissionsEnabled() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateCreateProjectSubmissionsEnabled()
	})
}

// SetViewResultsEnabled sets the "view_results_enabled" field.
func (u *HackathonStateUpsertOne) SetViewResultsEnabled(v bool) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetViewResultsEnabled(v)
	})
}

// UpdateViewResultsEnabled sets the "view_results_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateViewResultsEnabled() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateViewResultsEnabled()
	})
}

// SetViewTeamsEnabled sets the "view_teams_enabled" field.
func (u *HackathonStateUpsertOne) SetViewTeamsEnabled(v bool) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetViewTeamsEnabled(v)
	})
}

// UpdateViewTeamsEnabled sets the "view_teams_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateViewTeamsEnabled() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateViewTeamsEnabled()
	})
}

// SetModifiedAt sets the "modified_at" field.
func (u *HackathonStateUpsertOne) SetModifiedAt(v time.Time) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateModifiedAt() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateModifiedAt()
	})
}

// SetCurrentPhaseID sets the "current_phase_id" field.
func (u *HackathonStateUpsertOne) SetCurrentPhaseID(v uuid.UUID) *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetCurrentPhaseID(v)
	})
}

// UpdateCurrentPhaseID sets the "current_phase_id" field to the value that was provided on create.
func (u *HackathonStateUpsertOne) UpdateCurrentPhaseID() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateCurrentPhaseID()
	})
}

// ClearCurrentPhaseID clears the value of the "current_phase_id" field.
func (u *HackathonStateUpsertOne) ClearCurrentPhaseID() *HackathonStateUpsertOne {
	return u.Update(func(s *HackathonStateUpsert) {
		s.ClearCurrentPhaseID()
	})
}

// Exec executes the query.
func (u *HackathonStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HackathonStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HackathonStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HackathonStateUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: HackathonStateUpsertOne.ID is not supported by MySQL driver. Use HackathonStateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HackathonStateUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HackathonStateCreateBulk is the builder for creating many HackathonState entities in bulk.
type HackathonStateCreateBulk struct {
	config
	err      error
	builders []*HackathonStateCreate
	conflict []sql.ConflictOption
}

// Save creates the HackathonState entities in the database.
func (_c *HackathonStateCreateBulk) Save(ctx context.Context) ([]*HackathonState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HackathonState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HackathonStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HackathonStateCreateBulk) SaveX(ctx context.Context) []*HackathonState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HackathonStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HackathonStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HackathonState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HackathonStateUpsert) {
//			SetRegistrationsEnabled(v+v).
//		}).
//		Exec(ctx)
func (_c *HackathonStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *HackathonStateUpsertBulk {
	_c.conflict = opts
	return &HackathonStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HackathonState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HackathonStateCreateBulk) OnConflictColumns(columns ...string) *HackathonStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HackathonStateUpsertBulk{
		create: _c,
	}
}

// HackathonStateUpsertBulk is the builder for "upsert"-ing
// a bulk of HackathonState nodes.
type HackathonStateUpsertBulk struct {
	create *HackathonStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HackathonState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(hackathonstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *HackathonStateUpsertBulk) UpdateNewValues() *HackathonStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(hackathonstate.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(hackathonstate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HackathonState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HackathonStateUpsertBulk) Ignore() *HackathonStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HackathonStateUpsertBulk) DoNothing() *HackathonStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HackathonStateCreateBulk.OnConflict
// documentation for more info.
func (u *HackathonStateUpsertBulk) Update(set func(*HackathonStateUpsert)) *HackathonStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HackathonStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetRegistrationsEnabled sets the "registrations_enabled" field.
func (u *HackathonStateUpsertBulk) SetRegistrationsEnabled(v bool) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetRegistrationsEnabled(v)
	})
}

// UpdateRegistrationsEnabled sets the "registrations_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateRegistrationsEnabled() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateRegistrationsEnabled()
	})
}

// SetVotingEnabled sets the "voting_enabled" field.
func (u *HackathonStateUpsertBulk) SetVotingEnabled(v bool) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetVotingEnabled(v)
	})
}

// UpdateVotingEnabled sets the "voting_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateVotingEnabled() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateVotingEnabled()
	})
}

// SetProposeProjectsEnabled sets the "propose_projects_enabled" field.
func (u *HackathonStateUpsertBulk) SetProposeProjectsEnabled(v bool) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetProposeProjectsEnabled(v)
	})
}

// UpdateProposeProjectsEnabled sets the "propose_projects_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateProposeProjectsEnabled() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateProposeProjectsEnabled()
	})
}

// SetSetTeamPreferencesEnabled sets the "set_team_preferences_enabled" field.
func (u *HackathonStateUpsertBulk) SetSetTeamPreferencesEnabled(v bool) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetSetTeamPreferencesEnabled(v)
	})
}

// UpdateSetTeamPreferencesEnabled sets the "set_team_preferences_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateSetTeamPreferencesEnabled() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateSetTeamPreferencesEnabled()
	})
}

// SetCreateProjectSubmissionsEnabled sets the "create_project_submissions_enabled" field.
func (u *HackathonStateUpsertBulk) SetCreateProjectSubmissionsEnabled(v bool) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetCreateProjectSubmissionsEnabled(v)
	})
}

// UpdateCreateProjectSubmissionsEnabled sets the "create_project_submissions_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateCreateProjectSubmissionsEnabled() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateCreateProjectSubmissionsEnabled()
	})
}

// SetViewResultsEnabled sets the "view_results_enabled" field.
func (u *HackathonStateUpsertBulk) SetViewResultsEnabled(v bool) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetViewResultsEnabled(v)
	})
}

// UpdateViewResultsEnabled sets the "view_results_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateViewResultsEnabled() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateViewResultsEnabled()
	})
}

// SetViewTeamsEnabled sets the "view_teams_enabled" field.
func (u *HackathonStateUpsertBulk) SetViewTeamsEnabled(v bool) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetViewTeamsEnabled(v)
	})
}

// UpdateViewTeamsEnabled sets the "view_teams_enabled" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateViewTeamsEnabled() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateViewTeamsEnabled()
	})
}

// SetModifiedAt sets the "modified_at" field.
func (u *HackathonStateUpsertBulk) SetModifiedAt(v time.Time) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateModifiedAt() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateModifiedAt()
	})
}

// SetCurrentPhaseID sets the "current_phase_id" field.
func (u *HackathonStateUpsertBulk) SetCurrentPhaseID(v uuid.UUID) *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.SetCurrentPhaseID(v)
	})
}

// UpdateCurrentPhaseID sets the "current_phase_id" field to the value that was provided on create.
func (u *HackathonStateUpsertBulk) UpdateCurrentPhaseID() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.UpdateCurrentPhaseID()
	})
}

// ClearCurrentPhaseID clears the value of the "current_phase_id" field.
func (u *HackathonStateUpsertBulk) ClearCurrentPhaseID() *HackathonStateUpsertBulk {
	return u.Update(func(s *HackathonStateUpsert) {
		s.ClearCurrentPhaseID()
	})
}

// Exec executes the query.
func (u *HackathonStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HackathonStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HackathonStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HackathonStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
