// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathon"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathonstate"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/user"
)

// A hackathon event containing tracks, projects, phases, and participants.
type Hackathon struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Display name of the hackathon, must be unique.
	Name string `json:"name,omitempty"`
	// Scheduled start time; nil if not yet scheduled.
	StartsAt *time.Time `json:"starts_at,omitempty"`
	// Scheduled end time; nil if not yet scheduled.
	EndsAt *time.Time `json:"ends_at,omitempty"`
	// Timestamp when the hackathon was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Timestamp of the last modification.
	ModifiedAt time.Time `json:"modified_at,omitempty"`
	// Controls whether non-participants can discover this hackathon.
	Visibility hackathon.Visibility `json:"visibility,omitempty"`
	// Detailed description of the hackathon, supports rich text.
	Description string `json:"description,omitempty"`
	// URL or path to the hackathon logo image.
	Logo string `json:"logo,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HackathonQuery when eager-loading is set.
	Edges                    HackathonEdges `json:"edges"`
	phase_current_of         *uuid.UUID
	user_created_hackathons  *uuid.UUID
	user_modified_hackathons *uuid.UUID
	selectValues             sql.SelectValues
}

// HackathonEdges holds the relations/edges for other nodes in the graph.
type HackathonEdges struct {
	// Thematic tracks within this hackathon.
	Tracks []*Track `json:"tracks,omitempty"`
	// Projects submitted to this hackathon.
	Projects []*Project `json:"projects,omitempty"`
	// Users who are participating or waitlisted.
	ParticipatingUsers []*User `json:"participating_users,omitempty"`
	// Content pages associated with this hackathon.
	Pages []*Page `json:"pages,omitempty"`
	// Temporal phases (e.g. ideation, hacking, judging).
	Phases []*Phase `json:"phases,omitempty"`
	// Configuration state for this hackathon.
	State *HackathonState `json:"state,omitempty"`
	// Voting categories scoped to this hackathon.
	VoteCategories []*VoteCategory `json:"vote_categories,omitempty"`
	// Users who are owners of this hackathon (in addition to the creator).
	Owners []*User `json:"owners,omitempty"`
	// The user who created this hackathon.
	Creator *User `json:"creator,omitempty"`
	// The user who last modified this hackathon.
	Modifier *User `json:"modifier,omitempty"`
	// Participants holds the value of the participants edge.
	Participants []*Participant `json:"participants,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [11]bool
}

// TracksOrErr returns the Tracks value or an error if the edge
// was not loaded in eager-loading.
func (e HackathonEdges) TracksOrErr() ([]*Track, error) {
	if e.loadedTypes[0] {
		return e.Tracks, nil
	}
	return nil, &NotLoadedError{edge: "tracks"}
}

// ProjectsOrErr returns the Projects value or an error if the edge
// was not loaded in eager-loading.
func (e HackathonEdges) ProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[1] {
		return e.Projects, nil
	}
	return nil, &NotLoadedError{edge: "projects"}
}

// ParticipatingUsersOrErr returns the ParticipatingUsers value or an error if the edge
// was not loaded in eager-loading.
func (e HackathonEdges) ParticipatingUsersOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.ParticipatingUsers, nil
	}
	return nil, &NotLoadedError{edge: "participating_users"}
}

// PagesOrErr returns the Pages value or an error if the edge
// was not loaded in eager-loading.
func (e HackathonEdges) PagesOrErr() ([]*Page, error) {
	if e.loadedTypes[3] {
		return e.Pages, nil
	}
	return nil, &NotLoadedError{edge: "pages"}
}

// PhasesOrErr returns the Phases value or an error if the edge
// was not loaded in eager-loading.
func (e HackathonEdges) PhasesOrErr() ([]*Phase, error) {
	if e.loadedTypes[4] {
		return e.Phases, nil
	}
	return nil, &NotLoadedError{edge: "phases"}
}

// StateOrErr returns the State value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HackathonEdges) StateOrErr() (*HackathonState, error) {
	if e.State != nil {
		return e.State, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: hackathonstate.Label}
	}
	return nil, &NotLoadedError{edge: "state"}
}

// VoteCategoriesOrErr returns the VoteCategories value or an error if the edge
// was not loaded in eager-loading.
func (e HackathonEdges) VoteCategoriesOrErr() ([]*VoteCategory, error) {
	if e.loadedTypes[6] {
		return e.VoteCategories, nil
	}
	return nil, &NotLoadedError{edge: "vote_categories"}
}

// OwnersOrErr returns the Owners value or an error if the edge
// was not loaded in eager-loading.
func (e HackathonEdges) OwnersOrErr() ([]*User, error) {
	if e.loadedTypes[7] {
		return e.Owners, nil
	}
	return nil, &NotLoadedError{edge: "owners"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HackathonEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[8] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// ModifierOrErr returns the Modifier value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HackathonEdges) ModifierOrErr() (*User, error) {
	if e.Modifier != nil {
		return e.Modifier, nil
	} else if e.loadedTypes[9] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "modifier"}
}

// ParticipantsOrErr returns the Participants value or an error if the edge
// was not loaded in eager-loading.
func (e HackathonEdges) ParticipantsOrErr() ([]*Participant, error) {
	if e.loadedTypes[10] {
		return e.Participants, nil
	}
	return nil, &NotLoadedError{edge: "participants"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Hackathon) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hackathon.FieldName, hackathon.FieldVisibility, hackathon.FieldDescription, hackathon.FieldLogo:
			values[i] = new(sql.NullString)
		case hackathon.FieldStartsAt, hackathon.FieldEndsAt, hackathon.FieldCreatedAt, hackathon.FieldModifiedAt:
			values[i] = new(sql.NullTime)
		case hackathon.FieldID:
			values[i] = new(uuid.UUID)
		case hackathon.ForeignKeys[0]: // phase_current_of
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case hackathon.ForeignKeys[1]: // user_created_hackathons
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case hackathon.ForeignKeys[2]: // user_modified_hackathons
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Hackathon fields.
func (_m *Hackathon) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hackathon.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case hackathon.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case hackathon.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = new(time.Time)
				*_m.StartsAt = value.Time
			}
		case hackathon.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = new(time.Time)
				*_m.EndsAt = value.Time
			}
		case hackathon.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case hackathon.FieldModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field modified_at", values[i])
			} else if value.Valid {
				_m.ModifiedAt = value.Time
			}
		case hackathon.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = hackathon.Visibility(value.String)
			}
		case hackathon.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case hackathon.FieldLogo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo", values[i])
			} else if value.Valid {
				_m.Logo = value.String
			}
		case hackathon.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field phase_current_of", values[i])
			} else if value.Valid {
				_m.phase_current_of = new(uuid.UUID)
				*_m.phase_current_of = *value.S.(*uuid.UUID)
			}
		case hackathon.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_created_hackathons", values[i])
			} else if value.Valid {
				_m.user_created_hackathons = new(uuid.UUID)
				*_m.user_created_hackathons = *value.S.(*uuid.UUID)
			}
		case hackathon.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_modified_hackathons", values[i])
			} else if value.Valid {
				_m.user_modified_hackathons = new(uuid.UUID)
				*_m.user_modified_hackathons = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Hackathon.
// This includes values selected through modifiers, order, etc.
func (_m *Hackathon) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTracks queries the "tracks" edge of the Hackathon entity.
func (_m *Hackathon) QueryTracks() *TrackQuery {
	return NewHackathonClient(_m.config).QueryTracks(_m)
}

// QueryProjects queries the "projects" edge of the Hackathon entity.
func (_m *Hackathon) QueryProjects() *ProjectQuery {
	return NewHackathonClient(_m.config).QueryProjects(_m)
}

// QueryParticipatingUsers queries the "participating_users" edge of the Hackathon entity.
func (_m *Hackathon) QueryParticipatingUsers() *UserQuery {
	return NewHackathonClient(_m.config).QueryParticipatingUsers(_m)
}

// QueryPages queries the "pages" edge of the Hackathon entity.
func (_m *Hackathon) QueryPages() *PageQuery {
	return NewHackathonClient(_m.config).QueryPages(_m)
}

// QueryPhases queries the "phases" edge of the Hackathon entity.
func (_m *Hackathon) QueryPhases() *PhaseQuery {
	return NewHackathonClient(_m.config).QueryPhases(_m)
}

// QueryState queries the "state" edge of the Hackathon entity.
func (_m *Hackathon) QueryState() *HackathonStateQuery {
	return NewHackathonClient(_m.config).QueryState(_m)
}

// QueryVoteCategories queries the "vote_categories" edge of the Hackathon entity.
func (_m *Hackathon) QueryVoteCategories() *VoteCategoryQuery {
	return NewHackathonClient(_m.config).QueryVoteCategories(_m)
}

// QueryOwners queries the "owners" edge of the Hackathon entity.
func (_m *Hackathon) QueryOwners() *UserQuery {
	return NewHackathonClient(_m.config).QueryOwners(_m)
}

// QueryCreator queries the "creator" edge of the Hackathon entity.
func (_m *Hackathon) QueryCreator() *UserQuery {
	return NewHackathonClient(_m.config).QueryCreator(_m)
}

// QueryModifier queries the "modifier" edge of the Hackathon entity.
func (_m *Hackathon) QueryModifier() *UserQuery {
	return NewHackathonClient(_m.config).QueryModifier(_m)
}

// QueryParticipants queries the "participants" edge of the Hackathon entity.
func (_m *Hackathon) QueryParticipants() *ParticipantQuery {
	return NewHackathonClient(_m.config).QueryParticipants(_m)
}

// Update returns a builder for updating this Hackathon.
// Note that you need to call Hackathon.Unwrap() before calling this method if this Hackathon
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Hackathon) Update() *HackathonUpdateOne {
	return NewHackathonClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Hackathon entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Hackathon) Unwrap() *Hackathon {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Hackathon is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Hackathon) String() string {
	var builder strings.Builder
	builder.WriteString("Hackathon(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.StartsAt; v != nil {
		builder.WriteString("starts_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndsAt; v != nil {
		builder.WriteString("ends_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("modified_at=")
	builder.WriteString(_m.ModifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(fmt.Sprintf("%v", _m.Visibility))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("logo=")
	builder.WriteString(_m.Logo)
	builder.WriteByte(')')
	return builder.String()
}

// Hackathons is a parsable slice of Hackathon.
type Hackathons []*Hackathon
