// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathon"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/page"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/phase"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/predicate"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/user"
)

// PageUpdate is the builder for updating Page entities.
type PageUpdate struct {
	config
	hooks    []Hook
	mutation *PageMutation
}

// Where appends a list predicates to the PageUpdate builder.
func (_u *PageUpdate) Where(ps ...predicate.Page) *PageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PageUpdate) SetTitle(v string) *PageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PageUpdate) SetNillableTitle(v *string) *PageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PageUpdate) SetContent(v string) *PageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PageUpdate) SetNillableContent(v *string) *PageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetVisible sets the "visible" field.
func (_u *PageUpdate) SetVisible(v bool) *PageUpdate {
	_u.mutation.SetVisible(v)
	return _u
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_u *PageUpdate) SetNillableVisible(v *bool) *PageUpdate {
	if v != nil {
		_u.SetVisible(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *PageUpdate) SetOrder(v int) *PageUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *PageUpdate) SetNillableOrder(v *int) *PageUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *PageUpdate) AddOrder(v int) *PageUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *PageUpdate) SetModifiedAt(v time.Time) *PageUpdate {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_u *PageUpdate) SetNillableModifiedAt(v *time.Time) *PageUpdate {
	if v != nil {
		_u.SetModifiedAt(*v)
	}
	return _u
}

// AddHackathonIDs adds the "hackathon" edge to the Hackathon entity by IDs.
func (_u *PageUpdate) AddHackathonIDs(ids ...int) *PageUpdate {
	_u.mutation.AddHackathonIDs(ids...)
	return _u
}

// AddHackathon adds the "hackathon" edges to the Hackathon entity.
func (_u *PageUpdate) AddHackathon(v ...*Hackathon) *PageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHackathonIDs(ids...)
}

// AddPhaseIDs adds the "phases" edge to the Phase entity by IDs.
func (_u *PageUpdate) AddPhaseIDs(ids ...int) *PageUpdate {
	_u.mutation.AddPhaseIDs(ids...)
	return _u
}

// AddPhases adds the "phases" edges to the Phase entity.
func (_u *PageUpdate) AddPhases(v ...*Phase) *PageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPhaseIDs(ids...)
}

// SetModifierID sets the "modifier" edge to the User entity by ID.
func (_u *PageUpdate) SetModifierID(id int) *PageUpdate {
	_u.mutation.SetModifierID(id)
	return _u
}

// SetNillableModifierID sets the "modifier" edge to the User entity by ID if the given value is not nil.
func (_u *PageUpdate) SetNillableModifierID(id *int) *PageUpdate {
	if id != nil {
		_u = _u.SetModifierID(*id)
	}
	return _u
}

// SetModifier sets the "modifier" edge to the User entity.
func (_u *PageUpdate) SetModifier(v *User) *PageUpdate {
	return _u.SetModifierID(v.ID)
}

// Mutation returns the PageMutation object of the builder.
func (_u *PageUpdate) Mutation() *PageMutation {
	return _u.mutation
}

// ClearHackathon clears all "hackathon" edges to the Hackathon entity.
func (_u *PageUpdate) ClearHackathon() *PageUpdate {
	_u.mutation.ClearHackathon()
	return _u
}

// RemoveHackathonIDs removes the "hackathon" edge to Hackathon entities by IDs.
func (_u *PageUpdate) RemoveHackathonIDs(ids ...int) *PageUpdate {
	_u.mutation.RemoveHackathonIDs(ids...)
	return _u
}

// RemoveHackathon removes "hackathon" edges to Hackathon entities.
func (_u *PageUpdate) RemoveHackathon(v ...*Hackathon) *PageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHackathonIDs(ids...)
}

// ClearPhases clears all "phases" edges to the Phase entity.
func (_u *PageUpdate) ClearPhases() *PageUpdate {
	_u.mutation.ClearPhases()
	return _u
}

// RemovePhaseIDs removes the "phases" edge to Phase entities by IDs.
func (_u *PageUpdate) RemovePhaseIDs(ids ...int) *PageUpdate {
	_u.mutation.RemovePhaseIDs(ids...)
	return _u
}

// RemovePhases removes "phases" edges to Phase entities.
func (_u *PageUpdate) RemovePhases(v ...*Phase) *PageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePhaseIDs(ids...)
}

// ClearModifier clears the "modifier" edge to the User entity.
func (_u *PageUpdate) ClearModifier() *PageUpdate {
	_u.mutation.ClearModifier()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PageUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := page.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Page.title": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Page.creator"`)
	}
	return nil
}

func (_u *PageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(page.Table, page.Columns, sqlgraph.NewFieldSpec(page.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(page.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(page.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visible(); ok {
		_spec.SetField(page.FieldVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(page.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(page.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(page.FieldModifiedAt, field.TypeTime, value)
	}
	if _u.mutation.HackathonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   page.HackathonTable,
			Columns: page.HackathonPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHackathonIDs(); len(nodes) > 0 && !_u.mutation.HackathonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   page.HackathonTable,
			Columns: page.HackathonPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HackathonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   page.HackathonTable,
			Columns: page.HackathonPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.PhasesTable,
			Columns: page.PhasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPhasesIDs(); len(nodes) > 0 && !_u.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.PhasesTable,
			Columns: page.PhasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.PhasesTable,
			Columns: page.PhasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ModifierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ModifierTable,
			Columns: []string{page.ModifierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModifierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ModifierTable,
			Columns: []string{page.ModifierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{page.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PageUpdateOne is the builder for updating a single Page entity.
type PageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PageMutation
}

// SetTitle sets the "title" field.
func (_u *PageUpdateOne) SetTitle(v string) *PageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableTitle(v *string) *PageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PageUpdateOne) SetContent(v string) *PageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableContent(v *string) *PageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetVisible sets the "visible" field.
func (_u *PageUpdateOne) SetVisible(v bool) *PageUpdateOne {
	_u.mutation.SetVisible(v)
	return _u
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableVisible(v *bool) *PageUpdateOne {
	if v != nil {
		_u.SetVisible(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *PageUpdateOne) SetOrder(v int) *PageUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableOrder(v *int) *PageUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *PageUpdateOne) AddOrder(v int) *PageUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *PageUpdateOne) SetModifiedAt(v time.Time) *PageUpdateOne {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableModifiedAt(v *time.Time) *PageUpdateOne {
	if v != nil {
		_u.SetModifiedAt(*v)
	}
	return _u
}

// AddHackathonIDs adds the "hackathon" edge to the Hackathon entity by IDs.
func (_u *PageUpdateOne) AddHackathonIDs(ids ...int) *PageUpdateOne {
	_u.mutation.AddHackathonIDs(ids...)
	return _u
}

// AddHackathon adds the "hackathon" edges to the Hackathon entity.
func (_u *PageUpdateOne) AddHackathon(v ...*Hackathon) *PageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHackathonIDs(ids...)
}

// AddPhaseIDs adds the "phases" edge to the Phase entity by IDs.
func (_u *PageUpdateOne) AddPhaseIDs(ids ...int) *PageUpdateOne {
	_u.mutation.AddPhaseIDs(ids...)
	return _u
}

// AddPhases adds the "phases" edges to the Phase entity.
func (_u *PageUpdateOne) AddPhases(v ...*Phase) *PageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPhaseIDs(ids...)
}

// SetModifierID sets the "modifier" edge to the User entity by ID.
func (_u *PageUpdateOne) SetModifierID(id int) *PageUpdateOne {
	_u.mutation.SetModifierID(id)
	return _u
}

// SetNillableModifierID sets the "modifier" edge to the User entity by ID if the given value is not nil.
func (_u *PageUpdateOne) SetNillableModifierID(id *int) *PageUpdateOne {
	if id != nil {
		_u = _u.SetModifierID(*id)
	}
	return _u
}

// SetModifier sets the "modifier" edge to the User entity.
func (_u *PageUpdateOne) SetModifier(v *User) *PageUpdateOne {
	return _u.SetModifierID(v.ID)
}

// Mutation returns the PageMutation object of the builder.
func (_u *PageUpdateOne) Mutation() *PageMutation {
	return _u.mutation
}

// ClearHackathon clears all "hackathon" edges to the Hackathon entity.
func (_u *PageUpdateOne) ClearHackathon() *PageUpdateOne {
	_u.mutation.ClearHackathon()
	return _u
}

// RemoveHackathonIDs removes the "hackathon" edge to Hackathon entities by IDs.
func (_u *PageUpdateOne) RemoveHackathonIDs(ids ...int) *PageUpdateOne {
	_u.mutation.RemoveHackathonIDs(ids...)
	return _u
}

// RemoveHackathon removes "hackathon" edges to Hackathon entities.
func (_u *PageUpdateOne) RemoveHackathon(v ...*Hackathon) *PageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHackathonIDs(ids...)
}

// ClearPhases clears all "phases" edges to the Phase entity.
func (_u *PageUpdateOne) ClearPhases() *PageUpdateOne {
	_u.mutation.ClearPhases()
	return _u
}

// RemovePhaseIDs removes the "phases" edge to Phase entities by IDs.
func (_u *PageUpdateOne) RemovePhaseIDs(ids ...int) *PageUpdateOne {
	_u.mutation.RemovePhaseIDs(ids...)
	return _u
}

// RemovePhases removes "phases" edges to Phase entities.
func (_u *PageUpdateOne) RemovePhases(v ...*Phase) *PageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePhaseIDs(ids...)
}

// ClearModifier clears the "modifier" edge to the User entity.
func (_u *PageUpdateOne) ClearModifier() *PageUpdateOne {
	_u.mutation.ClearModifier()
	return _u
}

// Where appends a list predicates to the PageUpdate builder.
func (_u *PageUpdateOne) Where(ps ...predicate.Page) *PageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PageUpdateOne) Select(field string, fields ...string) *PageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Page entity.
func (_u *PageUpdateOne) Save(ctx context.Context) (*Page, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PageUpdateOne) SaveX(ctx context.Context) *Page {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PageUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := page.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Page.title": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Page.creator"`)
	}
	return nil
}

func (_u *PageUpdateOne) sqlSave(ctx context.Context) (_node *Page, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(page.Table, page.Columns, sqlgraph.NewFieldSpec(page.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Page.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, page.FieldID)
		for _, f := range fields {
			if !page.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != page.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(page.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(page.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visible(); ok {
		_spec.SetField(page.FieldVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(page.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(page.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(page.FieldModifiedAt, field.TypeTime, value)
	}
	if _u.mutation.HackathonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   page.HackathonTable,
			Columns: page.HackathonPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHackathonIDs(); len(nodes) > 0 && !_u.mutation.HackathonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   page.HackathonTable,
			Columns: page.HackathonPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HackathonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   page.HackathonTable,
			Columns: page.HackathonPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.PhasesTable,
			Columns: page.PhasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPhasesIDs(); len(nodes) > 0 && !_u.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.PhasesTable,
			Columns: page.PhasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   page.PhasesTable,
			Columns: page.PhasesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phase.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ModifierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ModifierTable,
			Columns: []string{page.ModifierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModifierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ModifierTable,
			Columns: []string{page.ModifierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Page{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{page.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
