// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathon"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/participant"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/user"
)

// Participant is the model entity for the Participant schema.
type Participant struct {
	config `json:"-"`
	// HackathonID holds the value of the "hackathon_id" field.
	HackathonID int `json:"hackathon_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// IsWaiting holds the value of the "is_waiting" field.
	IsWaiting bool `json:"is_waiting,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ParticipantQuery when eager-loading is set.
	Edges        ParticipantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ParticipantEdges holds the relations/edges for other nodes in the graph.
type ParticipantEdges struct {
	// Hackathon holds the value of the hackathon edge.
	Hackathon *Hackathon `json:"hackathon,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// HackathonOrErr returns the Hackathon value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ParticipantEdges) HackathonOrErr() (*Hackathon, error) {
	if e.Hackathon != nil {
		return e.Hackathon, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: hackathon.Label}
	}
	return nil, &NotLoadedError{edge: "hackathon"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ParticipantEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Participant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case participant.FieldIsWaiting:
			values[i] = new(sql.NullBool)
		case participant.FieldHackathonID, participant.FieldUserID:
			values[i] = new(sql.NullInt64)
		case participant.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Participant fields.
func (_m *Participant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case participant.FieldHackathonID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hackathon_id", values[i])
			} else if value.Valid {
				_m.HackathonID = int(value.Int64)
			}
		case participant.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case participant.FieldIsWaiting:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_waiting", values[i])
			} else if value.Valid {
				_m.IsWaiting = value.Bool
			}
		case participant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Participant.
// This includes values selected through modifiers, order, etc.
func (_m *Participant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHackathon queries the "hackathon" edge of the Participant entity.
func (_m *Participant) QueryHackathon() *HackathonQuery {
	return NewParticipantClient(_m.config).QueryHackathon(_m)
}

// QueryUser queries the "user" edge of the Participant entity.
func (_m *Participant) QueryUser() *UserQuery {
	return NewParticipantClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Participant.
// Note that you need to call Participant.Unwrap() before calling this method if this Participant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Participant) Update() *ParticipantUpdateOne {
	return NewParticipantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Participant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Participant) Unwrap() *Participant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Participant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Participant) String() string {
	var builder strings.Builder
	builder.WriteString("Participant(")
	builder.WriteString("hackathon_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HackathonID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("is_waiting=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsWaiting))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Participants is a parsable slice of Participant.
type Participants []*Participant
