// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathon"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/participant"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/user"
)

// ParticipantCreate is the builder for creating a Participant entity.
type ParticipantCreate struct {
	config
	mutation *ParticipantMutation
	hooks    []Hook
}

// SetHackathonID sets the "hackathon_id" field.
func (_c *ParticipantCreate) SetHackathonID(v int) *ParticipantCreate {
	_c.mutation.SetHackathonID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ParticipantCreate) SetUserID(v int) *ParticipantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetIsWaiting sets the "is_waiting" field.
func (_c *ParticipantCreate) SetIsWaiting(v bool) *ParticipantCreate {
	_c.mutation.SetIsWaiting(v)
	return _c
}

// SetNillableIsWaiting sets the "is_waiting" field if the given value is not nil.
func (_c *ParticipantCreate) SetNillableIsWaiting(v *bool) *ParticipantCreate {
	if v != nil {
		_c.SetIsWaiting(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ParticipantCreate) SetCreatedAt(v time.Time) *ParticipantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ParticipantCreate) SetNillableCreatedAt(v *time.Time) *ParticipantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetHackathon sets the "hackathon" edge to the Hackathon entity.
func (_c *ParticipantCreate) SetHackathon(v *Hackathon) *ParticipantCreate {
	return _c.SetHackathonID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ParticipantCreate) SetUser(v *User) *ParticipantCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ParticipantMutation object of the builder.
func (_c *ParticipantCreate) Mutation() *ParticipantMutation {
	return _c.mutation
}

// Save creates the Participant in the database.
func (_c *ParticipantCreate) Save(ctx context.Context) (*Participant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ParticipantCreate) SaveX(ctx context.Context) *Participant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParticipantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParticipantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ParticipantCreate) defaults() {
	if _, ok := _c.mutation.IsWaiting(); !ok {
		v := participant.DefaultIsWaiting
		_c.mutation.SetIsWaiting(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := participant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ParticipantCreate) check() error {
	if _, ok := _c.mutation.HackathonID(); !ok {
		return &ValidationError{Name: "hackathon_id", err: errors.New(`ent: missing required field "Participant.hackathon_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Participant.user_id"`)}
	}
	if _, ok := _c.mutation.IsWaiting(); !ok {
		return &ValidationError{Name: "is_waiting", err: errors.New(`ent: missing required field "Participant.is_waiting"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Participant.created_at"`)}
	}
	if len(_c.mutation.HackathonIDs()) == 0 {
		return &ValidationError{Name: "hackathon", err: errors.New(`ent: missing required edge "Participant.hackathon"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Participant.user"`)}
	}
	return nil
}

func (_c *ParticipantCreate) sqlSave(ctx context.Context) (*Participant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *ParticipantCreate) createSpec() (*Participant, *sqlgraph.CreateSpec) {
	var (
		_node = &Participant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(participant.Table, nil)
	)
	if value, ok := _c.mutation.IsWaiting(); ok {
		_spec.SetField(participant.FieldIsWaiting, field.TypeBool, value)
		_node.IsWaiting = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(participant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.HackathonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   participant.HackathonTable,
			Columns: []string{participant.HackathonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HackathonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   participant.UserTable,
			Columns: []string{participant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ParticipantCreateBulk is the builder for creating many Participant entities in bulk.
type ParticipantCreateBulk struct {
	config
	err      error
	builders []*ParticipantCreate
}

// Save creates the Participant entities in the database.
func (_c *ParticipantCreateBulk) Save(ctx context.Context) ([]*Participant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Participant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ParticipantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ParticipantCreateBulk) SaveX(ctx context.Context) []*Participant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParticipantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParticipantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
