// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathon"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathonstate"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/page"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/phase"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/user"
)

// A temporal phase of a hackathon (e.g. ideation, hacking, judging).
type Phase struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// When this phase begins; nil if not yet scheduled.
	StartsAt *time.Time `json:"starts_at,omitempty"`
	// When this phase ends; nil if not yet scheduled.
	EndsAt *time.Time `json:"ends_at,omitempty"`
	// Display name of the phase.
	Name string `json:"name,omitempty"`
	// Description of the phase and its objectives.
	Description string `json:"description,omitempty"`
	// Timestamp when the phase was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Timestamp of the last modification.
	ModifiedAt time.Time `json:"modified_at,omitempty"`
	// Capability tags for this phase, drawn from the same enum as HackathonState. Purely informational — does not auto-enable or disable any capability. Each value must be one of: register, propose_projects, set_team_preferences, create_project_submissions, vote, view_results.
	Capabilities []string `json:"capabilities,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PhaseQuery when eager-loading is set.
	Edges                PhaseEdges `json:"edges"`
	hackathon_phases     *uuid.UUID
	user_created_phases  *uuid.UUID
	user_modified_phases *uuid.UUID
	selectValues         sql.SelectValues
}

// PhaseEdges holds the relations/edges for other nodes in the graph.
type PhaseEdges struct {
	// The hackathon this phase belongs to.
	Hackathon *Hackathon `json:"hackathon,omitempty"`
	// Content page linked to this phase.
	Page *Page `json:"page,omitempty"`
	// The hackathon currently sitting in this phase, if an organizer has advanced to it. At most one in practice, since a phase belongs to exactly one hackathon.
	CurrentOf []*Hackathon `json:"current_of,omitempty"`
	// The user who created this phase.
	Creator *User `json:"creator,omitempty"`
	// The user who last modified this phase.
	Modifier *User `json:"modifier,omitempty"`
	// The hackathon that has this phase set as its current phase.
	CurrentState *HackathonState `json:"current_state,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// HackathonOrErr returns the Hackathon value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhaseEdges) HackathonOrErr() (*Hackathon, error) {
	if e.Hackathon != nil {
		return e.Hackathon, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: hackathon.Label}
	}
	return nil, &NotLoadedError{edge: "hackathon"}
}

// PageOrErr returns the Page value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhaseEdges) PageOrErr() (*Page, error) {
	if e.Page != nil {
		return e.Page, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: page.Label}
	}
	return nil, &NotLoadedError{edge: "page"}
}

// CurrentOfOrErr returns the CurrentOf value or an error if the edge
// was not loaded in eager-loading.
func (e PhaseEdges) CurrentOfOrErr() ([]*Hackathon, error) {
	if e.loadedTypes[2] {
		return e.CurrentOf, nil
	}
	return nil, &NotLoadedError{edge: "current_of"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhaseEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// ModifierOrErr returns the Modifier value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhaseEdges) ModifierOrErr() (*User, error) {
	if e.Modifier != nil {
		return e.Modifier, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "modifier"}
}

// CurrentStateOrErr returns the CurrentState value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PhaseEdges) CurrentStateOrErr() (*HackathonState, error) {
	if e.CurrentState != nil {
		return e.CurrentState, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: hackathonstate.Label}
	}
	return nil, &NotLoadedError{edge: "current_state"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Phase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case phase.FieldCapabilities:
			values[i] = new([]byte)
		case phase.FieldName, phase.FieldDescription:
			values[i] = new(sql.NullString)
		case phase.FieldStartsAt, phase.FieldEndsAt, phase.FieldCreatedAt, phase.FieldModifiedAt:
			values[i] = new(sql.NullTime)
		case phase.FieldID:
			values[i] = new(uuid.UUID)
		case phase.ForeignKeys[0]: // hackathon_phases
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case phase.ForeignKeys[1]: // user_created_phases
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case phase.ForeignKeys[2]: // user_modified_phases
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Phase fields.
func (_m *Phase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case phase.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case phase.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = new(time.Time)
				*_m.StartsAt = value.Time
			}
		case phase.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = new(time.Time)
				*_m.EndsAt = value.Time
			}
		case phase.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case phase.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case phase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case phase.FieldModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field modified_at", values[i])
			} else if value.Valid {
				_m.ModifiedAt = value.Time
			}
		case phase.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case phase.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field hackathon_phases", values[i])
			} else if value.Valid {
				_m.hackathon_phases = new(uuid.UUID)
				*_m.hackathon_phases = *value.S.(*uuid.UUID)
			}
		case phase.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_created_phases", values[i])
			} else if value.Valid {
				_m.user_created_phases = new(uuid.UUID)
				*_m.user_created_phases = *value.S.(*uuid.UUID)
			}
		case phase.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_modified_phases", values[i])
			} else if value.Valid {
				_m.user_modified_phases = new(uuid.UUID)
				*_m.user_modified_phases = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Phase.
// This includes values selected through modifiers, order, etc.
func (_m *Phase) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHackathon queries the "hackathon" edge of the Phase entity.
func (_m *Phase) QueryHackathon() *HackathonQuery {
	return NewPhaseClient(_m.config).QueryHackathon(_m)
}

// QueryPage queries the "page" edge of the Phase entity.
func (_m *Phase) QueryPage() *PageQuery {
	return NewPhaseClient(_m.config).QueryPage(_m)
}

// QueryCurrentOf queries the "current_of" edge of the Phase entity.
func (_m *Phase) QueryCurrentOf() *HackathonQuery {
	return NewPhaseClient(_m.config).QueryCurrentOf(_m)
}

// QueryCreator queries the "creator" edge of the Phase entity.
func (_m *Phase) QueryCreator() *UserQuery {
	return NewPhaseClient(_m.config).QueryCreator(_m)
}

// QueryModifier queries the "modifier" edge of the Phase entity.
func (_m *Phase) QueryModifier() *UserQuery {
	return NewPhaseClient(_m.config).QueryModifier(_m)
}

// QueryCurrentState queries the "current_state" edge of the Phase entity.
func (_m *Phase) QueryCurrentState() *HackathonStateQuery {
	return NewPhaseClient(_m.config).QueryCurrentState(_m)
}

// Update returns a builder for updating this Phase.
// Note that you need to call Phase.Unwrap() before calling this method if this Phase
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Phase) Update() *PhaseUpdateOne {
	return NewPhaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Phase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Phase) Unwrap() *Phase {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Phase is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Phase) String() string {
	var builder strings.Builder
	builder.WriteString("Phase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.StartsAt; v != nil {
		builder.WriteString("starts_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndsAt; v != nil {
		builder.WriteString("ends_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("modified_at=")
	builder.WriteString(_m.ModifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteByte(')')
	return builder.String()
}

// Phases is a parsable slice of Phase.
type Phases []*Phase
