// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/predicate"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/teamparticipant"
)

// TeamParticipantDelete is the builder for deleting a TeamParticipant entity.
type TeamParticipantDelete struct {
	config
	hooks    []Hook
	mutation *TeamParticipantMutation
}

// Where appends a list predicates to the TeamParticipantDelete builder.
func (_d *TeamParticipantDelete) Where(ps ...predicate.TeamParticipant) *TeamParticipantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TeamParticipantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamParticipantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TeamParticipantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teamparticipant.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TeamParticipantDeleteOne is the builder for deleting a single TeamParticipant entity.
type TeamParticipantDeleteOne struct {
	_d *TeamParticipantDelete
}

// Where appends a list predicates to the TeamParticipantDelete builder.
func (_d *TeamParticipantDeleteOne) Where(ps ...predicate.TeamParticipant) *TeamParticipantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TeamParticipantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamparticipant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeamParticipantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
