// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/predicate"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/submission"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/votecategory"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/voteresult"
)

// VoteResultQuery is the builder for querying VoteResult entities.
type VoteResultQuery struct {
	config
	ctx              *QueryContext
	order            []voteresult.OrderOption
	inters           []Interceptor
	predicates       []predicate.VoteResult
	withVoteCategory *VoteCategoryQuery
	withSubmission   *SubmissionQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VoteResultQuery builder.
func (_q *VoteResultQuery) Where(ps ...predicate.VoteResult) *VoteResultQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VoteResultQuery) Limit(limit int) *VoteResultQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VoteResultQuery) Offset(offset int) *VoteResultQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VoteResultQuery) Unique(unique bool) *VoteResultQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VoteResultQuery) Order(o ...voteresult.OrderOption) *VoteResultQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryVoteCategory chains the current query on the "vote_category" edge.
func (_q *VoteResultQuery) QueryVoteCategory() *VoteCategoryQuery {
	query := (&VoteCategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(voteresult.Table, voteresult.FieldID, selector),
			sqlgraph.To(votecategory.Table, votecategory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voteresult.VoteCategoryTable, voteresult.VoteCategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubmission chains the current query on the "submission" edge.
func (_q *VoteResultQuery) QuerySubmission() *SubmissionQuery {
	query := (&SubmissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(voteresult.Table, voteresult.FieldID, selector),
			sqlgraph.To(submission.Table, submission.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, voteresult.SubmissionTable, voteresult.SubmissionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VoteResult entity from the query.
// Returns a *NotFoundError when no VoteResult was found.
func (_q *VoteResultQuery) First(ctx context.Context) (*VoteResult, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{voteresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VoteResultQuery) FirstX(ctx context.Context) *VoteResult {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VoteResult ID from the query.
// Returns a *NotFoundError when no VoteResult ID was found.
func (_q *VoteResultQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{voteresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VoteResultQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VoteResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VoteResult entity is found.
// Returns a *NotFoundError when no VoteResult entities are found.
func (_q *VoteResultQuery) Only(ctx context.Context) (*VoteResult, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{voteresult.Label}
	default:
		return nil, &NotSingularError{voteresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VoteResultQuery) OnlyX(ctx context.Context) *VoteResult {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VoteResult ID in the query.
// Returns a *NotSingularError when more than one VoteResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VoteResultQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{voteresult.Label}
	default:
		err = &NotSingularError{voteresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VoteResultQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VoteResults.
func (_q *VoteResultQuery) All(ctx context.Context) ([]*VoteResult, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VoteResult, *VoteResultQuery]()
	return withInterceptors[[]*VoteResult](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VoteResultQuery) AllX(ctx context.Context) []*VoteResult {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VoteResult IDs.
func (_q *VoteResultQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(voteresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VoteResultQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VoteResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VoteResultQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VoteResultQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VoteResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VoteResultQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VoteResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VoteResultQuery) Clone() *VoteResultQuery {
	if _q == nil {
		return nil
	}
	return &VoteResultQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]voteresult.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.VoteResult{}, _q.predicates...),
		withVoteCategory: _q.withVoteCategory.Clone(),
		withSubmission:   _q.withSubmission.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithVoteCategory tells the query-builder to eager-load the nodes that are connected to
// the "vote_category" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VoteResultQuery) WithVoteCategory(opts ...func(*VoteCategoryQuery)) *VoteResultQuery {
	query := (&VoteCategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVoteCategory = query
	return _q
}

// WithSubmission tells the query-builder to eager-load the nodes that are connected to
// the "submission" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VoteResultQuery) WithSubmission(opts ...func(*SubmissionQuery)) *VoteResultQuery {
	query := (&SubmissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubmission = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Position int `json:"position,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VoteResult.Query().
//		GroupBy(voteresult.FieldPosition).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VoteResultQuery) GroupBy(field string, fields ...string) *VoteResultGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VoteResultGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = voteresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Position int `json:"position,omitempty"`
//	}
//
//	client.VoteResult.Query().
//		Select(voteresult.FieldPosition).
//		Scan(ctx, &v)
func (_q *VoteResultQuery) Select(fields ...string) *VoteResultSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VoteResultSelect{VoteResultQuery: _q}
	sbuild.label = voteresult.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VoteResultSelect configured with the given aggregations.
func (_q *VoteResultQuery) Aggregate(fns ...AggregateFunc) *VoteResultSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VoteResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !voteresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VoteResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VoteResult, error) {
	var (
		nodes       = []*VoteResult{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withVoteCategory != nil,
			_q.withSubmission != nil,
		}
	)
	if _q.withVoteCategory != nil || _q.withSubmission != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, voteresult.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VoteResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VoteResult{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withVoteCategory; query != nil {
		if err := _q.loadVoteCategory(ctx, query, nodes, nil,
			func(n *VoteResult, e *VoteCategory) { n.Edges.VoteCategory = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubmission; query != nil {
		if err := _q.loadSubmission(ctx, query, nodes, nil,
			func(n *VoteResult, e *Submission) { n.Edges.Submission = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VoteResultQuery) loadVoteCategory(ctx context.Context, query *VoteCategoryQuery, nodes []*VoteResult, init func(*VoteResult), assign func(*VoteResult, *VoteCategory)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*VoteResult)
	for i := range nodes {
		if nodes[i].vote_category_results == nil {
			continue
		}
		fk := *nodes[i].vote_category_results
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(votecategory.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "vote_category_results" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *VoteResultQuery) loadSubmission(ctx context.Context, query *SubmissionQuery, nodes []*VoteResult, init func(*VoteResult), assign func(*VoteResult, *Submission)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*VoteResult)
	for i := range nodes {
		if nodes[i].submission_vote_results == nil {
			continue
		}
		fk := *nodes[i].submission_vote_results
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(submission.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "submission_vote_results" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *VoteResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VoteResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(voteresult.Table, voteresult.Columns, sqlgraph.NewFieldSpec(voteresult.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voteresult.FieldID)
		for i := range fields {
			if fields[i] != voteresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VoteResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(voteresult.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = voteresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VoteResultGroupBy is the group-by builder for VoteResult entities.
type VoteResultGroupBy struct {
	selector
	build *VoteResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VoteResultGroupBy) Aggregate(fns ...AggregateFunc) *VoteResultGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VoteResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoteResultQuery, *VoteResultGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VoteResultGroupBy) sqlScan(ctx context.Context, root *VoteResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VoteResultSelect is the builder for selecting fields of VoteResult entities.
type VoteResultSelect struct {
	*VoteResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VoteResultSelect) Aggregate(fns ...AggregateFunc) *VoteResultSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VoteResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoteResultQuery, *VoteResultSelect](ctx, _s.VoteResultQuery, _s, _s.inters, v)
}

func (_s *VoteResultSelect) sqlScan(ctx context.Context, root *VoteResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
