// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/submission"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/votecategory"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/voteresult"
)

// VoteResultCreate is the builder for creating a VoteResult entity.
type VoteResultCreate struct {
	config
	mutation *VoteResultMutation
	hooks    []Hook
}

// SetPosition sets the "position" field.
func (_c *VoteResultCreate) SetPosition(v int) *VoteResultCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *VoteResultCreate) SetTitle(v string) *VoteResultCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *VoteResultCreate) SetNillableTitle(v *string) *VoteResultCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VoteResultCreate) SetCreatedAt(v time.Time) *VoteResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VoteResultCreate) SetNillableCreatedAt(v *time.Time) *VoteResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetModifiedAt sets the "modified_at" field.
func (_c *VoteResultCreate) SetModifiedAt(v time.Time) *VoteResultCreate {
	_c.mutation.SetModifiedAt(v)
	return _c
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_c *VoteResultCreate) SetNillableModifiedAt(v *time.Time) *VoteResultCreate {
	if v != nil {
		_c.SetModifiedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VoteResultCreate) SetID(v uuid.UUID) *VoteResultCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VoteResultCreate) SetNillableID(v *uuid.UUID) *VoteResultCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVoteCategoryID sets the "vote_category" edge to the VoteCategory entity by ID.
func (_c *VoteResultCreate) SetVoteCategoryID(id uuid.UUID) *VoteResultCreate {
	_c.mutation.SetVoteCategoryID(id)
	return _c
}

// SetVoteCategory sets the "vote_category" edge to the VoteCategory entity.
func (_c *VoteResultCreate) SetVoteCategory(v *VoteCategory) *VoteResultCreate {
	return _c.SetVoteCategoryID(v.ID)
}

// SetSubmissionID sets the "submission" edge to the Submission entity by ID.
func (_c *VoteResultCreate) SetSubmissionID(id uuid.UUID) *VoteResultCreate {
	_c.mutation.SetSubmissionID(id)
	return _c
}

// SetSubmission sets the "submission" edge to the Submission entity.
func (_c *VoteResultCreate) SetSubmission(v *Submission) *VoteResultCreate {
	return _c.SetSubmissionID(v.ID)
}

// Mutation returns the VoteResultMutation object of the builder.
func (_c *VoteResultCreate) Mutation() *VoteResultMutation {
	return _c.mutation
}

// Save creates the VoteResult in the database.
func (_c *VoteResultCreate) Save(ctx context.Context) (*VoteResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VoteResultCreate) SaveX(ctx context.Context) *VoteResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoteResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoteResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VoteResultCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := voteresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		v := voteresult.DefaultModifiedAt()
		_c.mutation.SetModifiedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := voteresult.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VoteResultCreate) check() error {
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "VoteResult.position"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VoteResult.created_at"`)}
	}
	if _, ok := _c.mutation.ModifiedAt(); !ok {
		return &ValidationError{Name: "modified_at", err: errors.New(`ent: missing required field "VoteResult.modified_at"`)}
	}
	if len(_c.mutation.VoteCategoryIDs()) == 0 {
		return &ValidationError{Name: "vote_category", err: errors.New(`ent: missing required edge "VoteResult.vote_category"`)}
	}
	if len(_c.mutation.SubmissionIDs()) == 0 {
		return &ValidationError{Name: "submission", err: errors.New(`ent: missing required edge "VoteResult.submission"`)}
	}
	return nil
}

func (_c *VoteResultCreate) sqlSave(ctx context.Context) (*VoteResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VoteResultCreate) createSpec() (*VoteResult, *sqlgraph.CreateSpec) {
	var (
		_node = &VoteResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(voteresult.Table, sqlgraph.NewFieldSpec(voteresult.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(voteresult.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(voteresult.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(voteresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ModifiedAt(); ok {
		_spec.SetField(voteresult.FieldModifiedAt, field.TypeTime, value)
		_node.ModifiedAt = value
	}
	if nodes := _c.mutation.VoteCategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteresult.VoteCategoryTable,
			Columns: []string{voteresult.VoteCategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(votecategory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vote_category_results = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubmissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voteresult.SubmissionTable,
			Columns: []string{voteresult.SubmissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(submission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.submission_vote_results = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VoteResultCreateBulk is the builder for creating many VoteResult entities in bulk.
type VoteResultCreateBulk struct {
	config
	err      error
	builders []*VoteResultCreate
}

// Save creates the VoteResult entities in the database.
func (_c *VoteResultCreateBulk) Save(ctx context.Context) ([]*VoteResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VoteResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VoteResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VoteResultCreateBulk) SaveX(ctx context.Context) []*VoteResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoteResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoteResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
