// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/hackathon"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/predicate"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/user"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/vote"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/votecategory"
	"github.com/swissdatasciencecenter/hackagon/components/backend/ent/voteresult"
)

// VoteCategoryUpdate is the builder for updating VoteCategory entities.
type VoteCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *VoteCategoryMutation
}

// Where appends a list predicates to the VoteCategoryUpdate builder.
func (_u *VoteCategoryUpdate) Where(ps ...predicate.VoteCategory) *VoteCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *VoteCategoryUpdate) SetName(v string) *VoteCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VoteCategoryUpdate) SetNillableName(v *string) *VoteCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *VoteCategoryUpdate) SetDescription(v string) *VoteCategoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *VoteCategoryUpdate) SetNillableDescription(v *string) *VoteCategoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *VoteCategoryUpdate) ClearDescription() *VoteCategoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetVotingMethod sets the "voting_method" field.
func (_u *VoteCategoryUpdate) SetVotingMethod(v votecategory.VotingMethod) *VoteCategoryUpdate {
	_u.mutation.SetVotingMethod(v)
	return _u
}

// SetNillableVotingMethod sets the "voting_method" field if the given value is not nil.
func (_u *VoteCategoryUpdate) SetNillableVotingMethod(v *votecategory.VotingMethod) *VoteCategoryUpdate {
	if v != nil {
		_u.SetVotingMethod(*v)
	}
	return _u
}

// SetVoterType sets the "voter_type" field.
func (_u *VoteCategoryUpdate) SetVoterType(v votecategory.VoterType) *VoteCategoryUpdate {
	_u.mutation.SetVoterType(v)
	return _u
}

// SetNillableVoterType sets the "voter_type" field if the given value is not nil.
func (_u *VoteCategoryUpdate) SetNillableVoterType(v *votecategory.VoterType) *VoteCategoryUpdate {
	if v != nil {
		_u.SetVoterType(*v)
	}
	return _u
}

// SetMaxPoints sets the "max_points" field.
func (_u *VoteCategoryUpdate) SetMaxPoints(v int) *VoteCategoryUpdate {
	_u.mutation.ResetMaxPoints()
	_u.mutation.SetMaxPoints(v)
	return _u
}

// SetNillableMaxPoints sets the "max_points" field if the given value is not nil.
func (_u *VoteCategoryUpdate) SetNillableMaxPoints(v *int) *VoteCategoryUpdate {
	if v != nil {
		_u.SetMaxPoints(*v)
	}
	return _u
}

// AddMaxPoints adds value to the "max_points" field.
func (_u *VoteCategoryUpdate) AddMaxPoints(v int) *VoteCategoryUpdate {
	_u.mutation.AddMaxPoints(v)
	return _u
}

// ClearMaxPoints clears the value of the "max_points" field.
func (_u *VoteCategoryUpdate) ClearMaxPoints() *VoteCategoryUpdate {
	_u.mutation.ClearMaxPoints()
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *VoteCategoryUpdate) SetModifiedAt(v time.Time) *VoteCategoryUpdate {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetHackathonID sets the "hackathon" edge to the Hackathon entity by ID.
func (_u *VoteCategoryUpdate) SetHackathonID(id uuid.UUID) *VoteCategoryUpdate {
	_u.mutation.SetHackathonID(id)
	return _u
}

// SetHackathon sets the "hackathon" edge to the Hackathon entity.
func (_u *VoteCategoryUpdate) SetHackathon(v *Hackathon) *VoteCategoryUpdate {
	return _u.SetHackathonID(v.ID)
}

// AddJuryMemberIDs adds the "jury_members" edge to the User entity by IDs.
func (_u *VoteCategoryUpdate) AddJuryMemberIDs(ids ...uuid.UUID) *VoteCategoryUpdate {
	_u.mutation.AddJuryMemberIDs(ids...)
	return _u
}

// AddJuryMembers adds the "jury_members" edges to the User entity.
func (_u *VoteCategoryUpdate) AddJuryMembers(v ...*User) *VoteCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJuryMemberIDs(ids...)
}

// AddVoteIDs adds the "votes" edge to the Vote entity by IDs.
func (_u *VoteCategoryUpdate) AddVoteIDs(ids ...uuid.UUID) *VoteCategoryUpdate {
	_u.mutation.AddVoteIDs(ids...)
	return _u
}

// AddVotes adds the "votes" edges to the Vote entity.
func (_u *VoteCategoryUpdate) AddVotes(v ...*Vote) *VoteCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteIDs(ids...)
}

// AddResultIDs adds the "results" edge to the VoteResult entity by IDs.
func (_u *VoteCategoryUpdate) AddResultIDs(ids ...uuid.UUID) *VoteCategoryUpdate {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the VoteResult entity.
func (_u *VoteCategoryUpdate) AddResults(v ...*VoteResult) *VoteCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the VoteCategoryMutation object of the builder.
func (_u *VoteCategoryUpdate) Mutation() *VoteCategoryMutation {
	return _u.mutation
}

// ClearHackathon clears the "hackathon" edge to the Hackathon entity.
func (_u *VoteCategoryUpdate) ClearHackathon() *VoteCategoryUpdate {
	_u.mutation.ClearHackathon()
	return _u
}

// ClearJuryMembers clears all "jury_members" edges to the User entity.
func (_u *VoteCategoryUpdate) ClearJuryMembers() *VoteCategoryUpdate {
	_u.mutation.ClearJuryMembers()
	return _u
}

// RemoveJuryMemberIDs removes the "jury_members" edge to User entities by IDs.
func (_u *VoteCategoryUpdate) RemoveJuryMemberIDs(ids ...uuid.UUID) *VoteCategoryUpdate {
	_u.mutation.RemoveJuryMemberIDs(ids...)
	return _u
}

// RemoveJuryMembers removes "jury_members" edges to User entities.
func (_u *VoteCategoryUpdate) RemoveJuryMembers(v ...*User) *VoteCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJuryMemberIDs(ids...)
}

// ClearVotes clears all "votes" edges to the Vote entity.
func (_u *VoteCategoryUpdate) ClearVotes() *VoteCategoryUpdate {
	_u.mutation.ClearVotes()
	return _u
}

// RemoveVoteIDs removes the "votes" edge to Vote entities by IDs.
func (_u *VoteCategoryUpdate) RemoveVoteIDs(ids ...uuid.UUID) *VoteCategoryUpdate {
	_u.mutation.RemoveVoteIDs(ids...)
	return _u
}

// RemoveVotes removes "votes" edges to Vote entities.
func (_u *VoteCategoryUpdate) RemoveVotes(v ...*Vote) *VoteCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteIDs(ids...)
}

// ClearResults clears all "results" edges to the VoteResult entity.
func (_u *VoteCategoryUpdate) ClearResults() *VoteCategoryUpdate {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to VoteResult entities by IDs.
func (_u *VoteCategoryUpdate) RemoveResultIDs(ids ...uuid.UUID) *VoteCategoryUpdate {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to VoteResult entities.
func (_u *VoteCategoryUpdate) RemoveResults(v ...*VoteResult) *VoteCategoryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VoteCategoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoteCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VoteCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoteCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VoteCategoryUpdate) defaults() {
	if _, ok := _u.mutation.ModifiedAt(); !ok {
		v := votecategory.UpdateDefaultModifiedAt()
		_u.mutation.SetModifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoteCategoryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := votecategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VoteCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VotingMethod(); ok {
		if err := votecategory.VotingMethodValidator(v); err != nil {
			return &ValidationError{Name: "voting_method", err: fmt.Errorf(`ent: validator failed for field "VoteCategory.voting_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VoterType(); ok {
		if err := votecategory.VoterTypeValidator(v); err != nil {
			return &ValidationError{Name: "voter_type", err: fmt.Errorf(`ent: validator failed for field "VoteCategory.voter_type": %w`, err)}
		}
	}
	if _u.mutation.HackathonCleared() && len(_u.mutation.HackathonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteCategory.hackathon"`)
	}
	return nil
}

func (_u *VoteCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(votecategory.Table, votecategory.Columns, sqlgraph.NewFieldSpec(votecategory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(votecategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(votecategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(votecategory.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.VotingMethod(); ok {
		_spec.SetField(votecategory.FieldVotingMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.VoterType(); ok {
		_spec.SetField(votecategory.FieldVoterType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MaxPoints(); ok {
		_spec.SetField(votecategory.FieldMaxPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPoints(); ok {
		_spec.AddField(votecategory.FieldMaxPoints, field.TypeInt, value)
	}
	if _u.mutation.MaxPointsCleared() {
		_spec.ClearField(votecategory.FieldMaxPoints, field.TypeInt)
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(votecategory.FieldModifiedAt, field.TypeTime, value)
	}
	if _u.mutation.HackathonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   votecategory.HackathonTable,
			Columns: []string{votecategory.HackathonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HackathonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   votecategory.HackathonTable,
			Columns: []string{votecategory.HackathonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JuryMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   votecategory.JuryMembersTable,
			Columns: votecategory.JuryMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJuryMembersIDs(); len(nodes) > 0 && !_u.mutation.JuryMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   votecategory.JuryMembersTable,
			Columns: votecategory.JuryMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JuryMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   votecategory.JuryMembersTable,
			Columns: votecategory.JuryMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.VotesTable,
			Columns: []string{votecategory.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVotesIDs(); len(nodes) > 0 && !_u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.VotesTable,
			Columns: []string{votecategory.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.VotesTable,
			Columns: []string{votecategory.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.ResultsTable,
			Columns: []string{votecategory.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteresult.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.ResultsTable,
			Columns: []string{votecategory.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.ResultsTable,
			Columns: []string{votecategory.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{votecategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VoteCategoryUpdateOne is the builder for updating a single VoteCategory entity.
type VoteCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VoteCategoryMutation
}

// SetName sets the "name" field.
func (_u *VoteCategoryUpdateOne) SetName(v string) *VoteCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VoteCategoryUpdateOne) SetNillableName(v *string) *VoteCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *VoteCategoryUpdateOne) SetDescription(v string) *VoteCategoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *VoteCategoryUpdateOne) SetNillableDescription(v *string) *VoteCategoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *VoteCategoryUpdateOne) ClearDescription() *VoteCategoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetVotingMethod sets the "voting_method" field.
func (_u *VoteCategoryUpdateOne) SetVotingMethod(v votecategory.VotingMethod) *VoteCategoryUpdateOne {
	_u.mutation.SetVotingMethod(v)
	return _u
}

// SetNillableVotingMethod sets the "voting_method" field if the given value is not nil.
func (_u *VoteCategoryUpdateOne) SetNillableVotingMethod(v *votecategory.VotingMethod) *VoteCategoryUpdateOne {
	if v != nil {
		_u.SetVotingMethod(*v)
	}
	return _u
}

// SetVoterType sets the "voter_type" field.
func (_u *VoteCategoryUpdateOne) SetVoterType(v votecategory.VoterType) *VoteCategoryUpdateOne {
	_u.mutation.SetVoterType(v)
	return _u
}

// SetNillableVoterType sets the "voter_type" field if the given value is not nil.
func (_u *VoteCategoryUpdateOne) SetNillableVoterType(v *votecategory.VoterType) *VoteCategoryUpdateOne {
	if v != nil {
		_u.SetVoterType(*v)
	}
	return _u
}

// SetMaxPoints sets the "max_points" field.
func (_u *VoteCategoryUpdateOne) SetMaxPoints(v int) *VoteCategoryUpdateOne {
	_u.mutation.ResetMaxPoints()
	_u.mutation.SetMaxPoints(v)
	return _u
}

// SetNillableMaxPoints sets the "max_points" field if the given value is not nil.
func (_u *VoteCategoryUpdateOne) SetNillableMaxPoints(v *int) *VoteCategoryUpdateOne {
	if v != nil {
		_u.SetMaxPoints(*v)
	}
	return _u
}

// AddMaxPoints adds value to the "max_points" field.
func (_u *VoteCategoryUpdateOne) AddMaxPoints(v int) *VoteCategoryUpdateOne {
	_u.mutation.AddMaxPoints(v)
	return _u
}

// ClearMaxPoints clears the value of the "max_points" field.
func (_u *VoteCategoryUpdateOne) ClearMaxPoints() *VoteCategoryUpdateOne {
	_u.mutation.ClearMaxPoints()
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *VoteCategoryUpdateOne) SetModifiedAt(v time.Time) *VoteCategoryUpdateOne {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetHackathonID sets the "hackathon" edge to the Hackathon entity by ID.
func (_u *VoteCategoryUpdateOne) SetHackathonID(id uuid.UUID) *VoteCategoryUpdateOne {
	_u.mutation.SetHackathonID(id)
	return _u
}

// SetHackathon sets the "hackathon" edge to the Hackathon entity.
func (_u *VoteCategoryUpdateOne) SetHackathon(v *Hackathon) *VoteCategoryUpdateOne {
	return _u.SetHackathonID(v.ID)
}

// AddJuryMemberIDs adds the "jury_members" edge to the User entity by IDs.
func (_u *VoteCategoryUpdateOne) AddJuryMemberIDs(ids ...uuid.UUID) *VoteCategoryUpdateOne {
	_u.mutation.AddJuryMemberIDs(ids...)
	return _u
}

// AddJuryMembers adds the "jury_members" edges to the User entity.
func (_u *VoteCategoryUpdateOne) AddJuryMembers(v ...*User) *VoteCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJuryMemberIDs(ids...)
}

// AddVoteIDs adds the "votes" edge to the Vote entity by IDs.
func (_u *VoteCategoryUpdateOne) AddVoteIDs(ids ...uuid.UUID) *VoteCategoryUpdateOne {
	_u.mutation.AddVoteIDs(ids...)
	return _u
}

// AddVotes adds the "votes" edges to the Vote entity.
func (_u *VoteCategoryUpdateOne) AddVotes(v ...*Vote) *VoteCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteIDs(ids...)
}

// AddResultIDs adds the "results" edge to the VoteResult entity by IDs.
func (_u *VoteCategoryUpdateOne) AddResultIDs(ids ...uuid.UUID) *VoteCategoryUpdateOne {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the VoteResult entity.
func (_u *VoteCategoryUpdateOne) AddResults(v ...*VoteResult) *VoteCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the VoteCategoryMutation object of the builder.
func (_u *VoteCategoryUpdateOne) Mutation() *VoteCategoryMutation {
	return _u.mutation
}

// ClearHackathon clears the "hackathon" edge to the Hackathon entity.
func (_u *VoteCategoryUpdateOne) ClearHackathon() *VoteCategoryUpdateOne {
	_u.mutation.ClearHackathon()
	return _u
}

// ClearJuryMembers clears all "jury_members" edges to the User entity.
func (_u *VoteCategoryUpdateOne) ClearJuryMembers() *VoteCategoryUpdateOne {
	_u.mutation.ClearJuryMembers()
	return _u
}

// RemoveJuryMemberIDs removes the "jury_members" edge to User entities by IDs.
func (_u *VoteCategoryUpdateOne) RemoveJuryMemberIDs(ids ...uuid.UUID) *VoteCategoryUpdateOne {
	_u.mutation.RemoveJuryMemberIDs(ids...)
	return _u
}

// RemoveJuryMembers removes "jury_members" edges to User entities.
func (_u *VoteCategoryUpdateOne) RemoveJuryMembers(v ...*User) *VoteCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJuryMemberIDs(ids...)
}

// ClearVotes clears all "votes" edges to the Vote entity.
func (_u *VoteCategoryUpdateOne) ClearVotes() *VoteCategoryUpdateOne {
	_u.mutation.ClearVotes()
	return _u
}

// RemoveVoteIDs removes the "votes" edge to Vote entities by IDs.
func (_u *VoteCategoryUpdateOne) RemoveVoteIDs(ids ...uuid.UUID) *VoteCategoryUpdateOne {
	_u.mutation.RemoveVoteIDs(ids...)
	return _u
}

// RemoveVotes removes "votes" edges to Vote entities.
func (_u *VoteCategoryUpdateOne) RemoveVotes(v ...*Vote) *VoteCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteIDs(ids...)
}

// ClearResults clears all "results" edges to the VoteResult entity.
func (_u *VoteCategoryUpdateOne) ClearResults() *VoteCategoryUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to VoteResult entities by IDs.
func (_u *VoteCategoryUpdateOne) RemoveResultIDs(ids ...uuid.UUID) *VoteCategoryUpdateOne {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to VoteResult entities.
func (_u *VoteCategoryUpdateOne) RemoveResults(v ...*VoteResult) *VoteCategoryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Where appends a list predicates to the VoteCategoryUpdate builder.
func (_u *VoteCategoryUpdateOne) Where(ps ...predicate.VoteCategory) *VoteCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VoteCategoryUpdateOne) Select(field string, fields ...string) *VoteCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VoteCategory entity.
func (_u *VoteCategoryUpdateOne) Save(ctx context.Context) (*VoteCategory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoteCategoryUpdateOne) SaveX(ctx context.Context) *VoteCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VoteCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoteCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VoteCategoryUpdateOne) defaults() {
	if _, ok := _u.mutation.ModifiedAt(); !ok {
		v := votecategory.UpdateDefaultModifiedAt()
		_u.mutation.SetModifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoteCategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := votecategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VoteCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VotingMethod(); ok {
		if err := votecategory.VotingMethodValidator(v); err != nil {
			return &ValidationError{Name: "voting_method", err: fmt.Errorf(`ent: validator failed for field "VoteCategory.voting_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VoterType(); ok {
		if err := votecategory.VoterTypeValidator(v); err != nil {
			return &ValidationError{Name: "voter_type", err: fmt.Errorf(`ent: validator failed for field "VoteCategory.voter_type": %w`, err)}
		}
	}
	if _u.mutation.HackathonCleared() && len(_u.mutation.HackathonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoteCategory.hackathon"`)
	}
	return nil
}

func (_u *VoteCategoryUpdateOne) sqlSave(ctx context.Context) (_node *VoteCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(votecategory.Table, votecategory.Columns, sqlgraph.NewFieldSpec(votecategory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VoteCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, votecategory.FieldID)
		for _, f := range fields {
			if !votecategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != votecategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(votecategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(votecategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(votecategory.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.VotingMethod(); ok {
		_spec.SetField(votecategory.FieldVotingMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.VoterType(); ok {
		_spec.SetField(votecategory.FieldVoterType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.MaxPoints(); ok {
		_spec.SetField(votecategory.FieldMaxPoints, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxPoints(); ok {
		_spec.AddField(votecategory.FieldMaxPoints, field.TypeInt, value)
	}
	if _u.mutation.MaxPointsCleared() {
		_spec.ClearField(votecategory.FieldMaxPoints, field.TypeInt)
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(votecategory.FieldModifiedAt, field.TypeTime, value)
	}
	if _u.mutation.HackathonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   votecategory.HackathonTable,
			Columns: []string{votecategory.HackathonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HackathonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   votecategory.HackathonTable,
			Columns: []string{votecategory.HackathonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hackathon.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JuryMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   votecategory.JuryMembersTable,
			Columns: votecategory.JuryMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJuryMembersIDs(); len(nodes) > 0 && !_u.mutation.JuryMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   votecategory.JuryMembersTable,
			Columns: votecategory.JuryMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JuryMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   votecategory.JuryMembersTable,
			Columns: votecategory.JuryMembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.VotesTable,
			Columns: []string{votecategory.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVotesIDs(); len(nodes) > 0 && !_u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.VotesTable,
			Columns: []string{votecategory.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.VotesTable,
			Columns: []string{votecategory.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.ResultsTable,
			Columns: []string{votecategory.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteresult.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.ResultsTable,
			Columns: []string{votecategory.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   votecategory.ResultsTable,
			Columns: []string{votecategory.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(voteresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VoteCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{votecategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
