[request_definition]
# request = the question you ask, "can user sub do action act on object obj in a specific hackathon"
r = sub, hackathon, obj, act

[policy_definition]
# policies define the rules that govern the system
# sub = a role or * wildcard
# hackathon = domain the policy applies to
# obj & act = the action allowed on object for the matched role&domain
p = sub, hackathon, obj, act

[role_definition]
# role definitions work through pattern matching, they are the "data" of the rbac system, the data that the policies work on
# g is for hackathon specific roles, of the form (user, role, domain)
# e.g. "g, alice, owner, hackathon1" means alice has role owner in hackathon1
g = _, _, _
# g2 is for global roles, e.g. "g2, adminuser, admin" means user "adminuser" has role admin in ALL domains
g2 = _, _

[policy_effect]
# this contains rules on how effects of policies are combined. We don't specify effects, so every policy has the default "allow" effect
# below rule just means allow action if any policy matches
e = some(where (p.eft == allow))

[matchers]
# this is the matcher logic for matching a request to one or more policies
# (g(r.sub, p.sub, r.hackathon) || p.sub=="*")
# this matches that the user has a specific role in a hackathon, or that the policy applies to all roles (e.g. hackathon 1 is read for all roles)
# keyMatch(r.hackathon, p.hackathon)
# this is a wildcard match on the hackathon, to allow rules to apply to all hackathons (e.g. role `member` is read on all hackathons). Mainly to cut down on number of rules
# r.obj == p.obj && r.act == p.act
# this just check that the object and action in the request and policy match
# || g2(r.sub, "admin")
# this overrides all of the other stuff and allows if a user has the admin role
m = (g(r.sub, p.sub, r.hackathon) || p.sub=="*") && keyMatch(r.hackathon, p.hackathon) && r.obj == p.obj && r.act == p.act || g2(r.sub, "admin")
